### ISSUE TITLE
请问你的标签格式是什么样的？可否给截图出来

### ISSUE THREAD

**Issue by gengyanlei** [hukaixuan19970627/YOLOv5_DOTA_OBB#1]

**Comment by hukaixuan19970627** [comment]
你速度太快了，知乎文章还没写完呢。
ReadMe.md中有说明
$  classid    x_c   y_c   longside   shortside    Θ    Θ∈[0, 180)


* longside: 旋转矩形框的最长边

* shortside: 与最长边对应的另一边

* Θ: x轴顺时针旋转遇到最长边所经过的角度
你可以参考 [DOTA_devkit_YOLO]（https://github.com/hukaixuan19970627/DOTA_devkit_YOLO），进行DOTA格式到YOLO长边表示法的转换。
![image](https://user-images.githubusercontent.com/72599120/111601549-6e374380-880d-11eb-97b0-8ea67bc26f16.png)

**Comment by gengyanlei** [comment]
@hukaixuan19970627 
好的，昨天刚看到你的知乎，因为我最近在探索一些旋转目标监测的开源项目。我可能看的太粗了，没注意到你的标签。
sorry

**Comment by gengyanlei** [comment]
你踩的角度定义-opencv的坑，我也踩过，不过你能这么详细的将整个流程记录下来，不错。我需要静下来，一点点修改代码了
