### ISSUE TITLE
使用自定义数据进行训练，P, R, mAP@.5, mAP@.5-.95, val_loss(box, obj, cls, angleloss)全程为0。想请问下作者是怎么解决呢？

### ISSUE THREAD

**Issue by Allenstin** [hukaixuan19970627/YOLOv5_DOTA_OBB#10]

**Comment by Allenstin** [comment]
数据制作格式，是按照作者的方式来的。label_index, x_c, y_c, longside, shortside, theta。数据集目前只有95张。数据使用作者代码进行过还原，是没有问题。训练的时候，train_batch.jpg也是没有问题。但是训练中，无论训练多少轮，后面的几位数字全程是0。如：“   103/149     3.33G    0.1998  0.002258         0   0.08696     0.289        66       640         0         0         0         0         0         0         0         0”。

**Comment by Allenstin** [comment]
刚看了下作者对其他问题的解答。感觉是数据集太少导致的结果，并且数据集角度不均衡导致的。我再搞点数据训练。希望没问题。不管怎样，十分感谢作者的贡献。

**Comment by hukaixuan19970627** [comment]
[
epoch/epochs-1 , mem , loss_obx , loss_obj ,  loss_cls  ,loss_angle ,
total_loss , targets_num , imgs.shape,  precision , recall , mAP@.5 ,  
mAP@.5-.95, val_loss_box, val_loss_obj, val_loss_cls， val_loss_angle
]
由于删除了在线评估程序，所以后续8个评估数据都是0是正常现象，旋转目标的评估方式比较特别，我另外写了一个evaluation.py。

**Comment by Allenstin** [comment]
作者的代码没有问题，我测试结果出来了。我把数据集简单copy了5分，到了600张后，训练300轮，已经可以在训练集上预测出结果了。训练的这些值“ 103/149 3.33G 0.1998 0.002258 0 0.08696 0.289 66 640 0 0 0 0 0 0 0 0”全为0不影响训练结果，但打印这块可能还是bug。再次感谢作者的代码。

**Comment by Allenstin** [comment]
> [
> epoch/epochs-1 , mem , loss_obx , loss_obj , loss_cls ,loss_angle ,
> total_loss , targets_num , imgs.shape, precision , recall , mAP@.5 ,
> mAP@.5-.95, val_loss_box, val_loss_obj, val_loss_cls， val_loss_angle
> ]
> 由于删除了在线评估程序，所以后续8个评估数据都是0是正常现象，旋转目标的评估方式比较特别，我另外写了一个evaluation.py。

谢谢作者的解答
