### ISSUE TITLE
图片格式的转换

### ISSUE THREAD

**Issue by suhanling** [hukaixuan19970627/YOLOv5_DOTA_OBB#102]
## ❔Question
大佬知乎上看到你的文章，想问下一些遥感图像的预处理 像一些数据集的标签预处理 提取 格式的转换的代码应该怎么去学写呢。

**Comment by hukaixuan19970627** [comment]
善用搜索引擎能解决99%的问题。

**Comment by hy2021022213** [comment]
作者有没有rolabelimg标定数据xml文件转为yolo可用txt的脚本呀？

**Comment by hukaixuan19970627** [comment]
> 作者有没有rolabelimg标定数据xml文件转为yolo可用txt的脚本呀？

没用过rolabelimg，你直接写一个呗
