### ISSUE TITLE
train_batch0/1/2中发现检测框发生偏移

### ISSUE THREAD

**Issue by isLucas** [hukaixuan19970627/YOLOv5_DOTA_OBB#103]
## ❔Question
大佬您好，我在训练自己训练集的时候发现检测框发生偏移了，请问这可能是哪些原因造成的呢？我猜想可能是因为我的图片尺寸不一致？我用您的转yolo格式工具转格式之后，在draw文件夹里检测框是没有发生偏移的。
如果大佬看到issue，有空的话请您帮我解答一下，谢谢您，这对我很重要！
P.S.：我尝试过把mosaic关闭，发现还是会发生偏移。我的数据集是单分类，按照您的帖子把nc改成了2进行训练。

![train_batch1](https://user-images.githubusercontent.com/30585108/139685640-c4c26743-cffb-4420-bbe5-8cd996b7003a.jpg)
![train_batch2](https://user-images.githubusercontent.com/30585108/139685653-20346432-64c9-4ba9-80a5-e3901335e312.jpg)
![train_batch1](https://user-images.githubusercontent.com/30585108/139685795-a8b0a8a2-a110-4ae2-9ad0-d5d94952b06f.jpg)

**Comment by hukaixuan19970627** [comment]
看起来似乎就是label标注的时候没贴合物体形状本身，所以求取最小外接矩形时计算得到的旋转角度有偏差。
你确定Draw里所有的图像（而不是一部分）都没问题吗，train_batch实际上就是把数据增强后的图像可视化出来而已。

**Comment by isLucas** [comment]
> 看起来似乎就是label标注的时候没贴合物体形状本身，所以求取最小外接矩形时计算得到的旋转角度有偏差。 你确定Draw里所有的图像（而不是一部分）都没问题吗，train_batch实际上就是把数据增强后的图像可视化出来而已。

大佬您好！谢谢您抽空回复我了。我又检查了一遍draw的数据，确定所有的图像都是贴合检测框的，不过有一些框似乎变形成平行四边形了 (如下图) 。会不会是在图像增强之后出错的，我去尝试把图像增强关掉之后效果如何。
![078_](https://user-images.githubusercontent.com/30585108/139857113-32c2bb1b-90a1-4d2e-b931-fad271215edf.png)

**Comment by isLucas** [comment]
我的数据集是用roLabelImg标注之后，转成dota格式再用您的代码转成yolo的

**Comment by isLucas** [comment]
大佬您好，又是我...我又双叒叕看了一遍您的知乎文章，按照评论所说的把图片高、宽统一之后再转换成yolo格式，并且把mosaic也关了，看train_batch0/1/2的情况，目前框的问题应该是解决了，如下图。
但是现在遇到了一个新的问题，我在predict的时候，即使predict训练集，也没有检测出半个物体，我按评论说的把检测的图片都resize成640 * 640 (没有变形) 之后也没用。我想请问下这会是什么原因呢？我使用的是Yolov5l的预训练权重。看result.png中的total loss，感觉应该不至于一个都检测不出来。。希望大佬看到的时候能帮我解答一下，十分感谢！
![train_batch0](https://user-images.githubusercontent.com/30585108/140027351-5170e756-7454-44de-9384-126a46a69c63.jpg)
![results](https://user-images.githubusercontent.com/30585108/140027390-c714cdfd-5cc1-40bc-8602-3fe6ebcf1aa3.png)

**Comment by hukaixuan19970627** [comment]
降低置信度的阈值看看，不至于一个都检测不出来的

**Comment by hy2021022213** [comment]
> 我的数据集是用roLabelImg标注之后，转成dota格式再用您的代码转成yolo的

你好，我也这里出现了问题，如果方便的话，可以把解决方案告知一下我吗？

**Comment by hukaixuan19970627** [comment]
有解决吗，我先关闭这个issue，如果还未解决的话可以reopen
