### ISSUE TITLE
DOTA_demo_view数据在哪里下载？

### ISSUE THREAD

**Issue by as754770178** [hukaixuan19970627/YOLOv5_DOTA_OBB#105]
工程中提示可以在release中下载，但是release中没有找到

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/140027713-1ad3edb8-22b8-4fe1-bfc4-1efe1ecb60ed.png)

**Comment by as754770178** [comment]
您好，提取码多少？
