### ISSUE TITLE
检测时，box尺寸过大

### ISSUE THREAD

**Issue by as754770178** [hukaixuan19970627/YOLOv5_DOTA_OBB#106]
您好，我下载`YOLOv5_DOTAv1.5_OBB.pt`和`train,detect_and_evaluate_demo_files`，运行`detect.py`脚本。
报错：
```
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'boxPoints'
> Overload resolution failed:
>  - Can't parse ''box' center point'. Sequence item with index 0 has a wrong type
```
我发现anchor尺寸为
```
anchors:
  - [10,13, 16,30, 33,23]  # P3/8
  - [30,61, 62,45, 59,119]  # P4/16
  - [116,90, 156,198, 373,326]  # P5/32
```
最后，一层计算得到box，会大于detect.py中设置输入尺寸1024。我怀疑是因为这个导致的，请教一下需要怎么修改？

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/140502176-ef357470-65bf-49f4-bf9d-9eac90344adb.png)

**Comment by as754770178** [comment]
多谢大佬，问题解决了
