### ISSUE TITLE
某些类的AP值异常

### ISSUE THREAD

**Issue by fzhq** [hukaixuan19970627/YOLOv5_DOTA_OBB#107]
## ❔Question
大佬,您好.我跑了您的模型,并在验证集进行了验证,但发现helicopter和soccer-ball-field的AP才不到30%,请问这是为什么呢?图片大小为512*512,gap50%

**Comment by hukaixuan19970627** [comment]
切成1024x1024

**Comment by fzhq** [comment]
> 切成1024x1024

好的,我试下.请问这样做的原理是什么呢?这俩个类也不算大物体把

**Comment by hukaixuan19970627** [comment]
> > 切成1024x1024
> 
> 好的,我试下.请问这样做的原理是什么呢?这俩个类也不算大物体把

异常指的是和正常结果不同，可参考的正常结果都是切成1024进行测试的。数据集没对齐无法做对比

**Comment by fzhq** [comment]
> > > 切成1024x1024
> > 
> > 
> > 好的,我试下.请问这样做的原理是什么呢?这俩个类也不算大物体把
> 
> 异常指的是和正常结果不同，可参考的正常结果都是切成1024进行测试的。数据集没对齐无法做对比

好的
