### ISSUE TITLE
请问你测的在这个模型下，mAP大概是多少？

### ISSUE THREAD

**Issue by lrh454830526** [hukaixuan19970627/YOLOv5_DOTA_OBB#109]
## ❔Question
我在dota数据集看到旋转框的MAP普遍在70%以上，但是使用当前这个模型mAP才60%左右 某些类的ap非常低，请问您有没有针对性的解决办法

**Comment by hukaixuan19970627** [comment]
https://github.com/hukaixuan19970627/YOLOv5_DOTA_OBB/issues/90

**Comment by lrh454830526** [comment]
> #90
好的谢谢大佬 另外一个问题 ，我的结果里面出现很多这种框
[![IfKIgg.png](https://z3.ax1x.com/2021/11/16/IfKIgg.png)](https://imgtu.com/i/IfKIgg)
就是两个相距很近的目标间会有这种重复框,检查过训练集数据,没有发现这种数据,看您的知乎文章说是对loss值做了相应的改进,请问大概是什么样的思路?
 #``

**Comment by hukaixuan19970627** [comment]
把改动的地方，trainbatch012，loss曲线等数据都发一下，只看检测的结果不好判断原因

**Comment by lrh454830526** [comment]
> 把改动的地方，trainbatch012，loss曲线等数据都发一下，只看检测的结果不好判断原因

数据集使用的DOTA2.0 比1.5多了两个类 helipad  airport
batch-size 4
使用DOTA_devkit把原始图片裁剪为1024*1024  gap为512
loss曲线变化如下
![image](https://user-images.githubusercontent.com/24297251/141958049-f55873a6-6d48-4867-afe5-483754fafaa6.png)
![image](https://user-images.githubusercontent.com/24297251/141958215-f83c3b9d-20dd-4b60-a61b-af865970e0ae.png)
以下是trainbatch012
![train_batch0](https://user-images.githubusercontent.com/24297251/141958542-07044c5b-e40b-4d6a-b836-37b7267d3dc8.jpg)

![train_batch1](https://user-images.githubusercontent.com/24297251/141958557-5021440e-788e-4765-9a8e-6ea17f33e87c.jpg)


![train_batch2](https://user-images.githubusercontent.com/24297251/141958494-e01eb433-9917-4964-adec-ad6f169f615d.jpg)

在YOLOv5x的基础上进行训练的  模型结构和训练超参上没有改变

**Comment by lrh454830526** [comment]
> 把改动的地方，trainbatch012，loss曲线等数据都发一下，只看检测的结果不好判断原因
不好意思 loss曲线发错了   是这个  中途断电训练中断过   所以后面是在前一个的基础上重新训练的
![image](https://user-images.githubusercontent.com/24297251/141961711-b30f3568-f20b-4e88-9573-c09eef8a3cf1.png)

**Comment by hukaixuan19970627** [comment]
你用这么大的模型啊，yolov5x我自己都没试过呢（设备显存吃紧）。
由于yolo系列比较特殊，没有基于imagenet的预训练模型，所以基本都需要train from scratch并且需要较大的epoch训练数。
DOTA数据集的话epoch设置为150~300差不多可以完全收敛，DOTAv2目标尺度分布范围较广，收敛难度也会加大，所以收敛所需epoch要大于200效果才比较好，看loss曲线的话确实还有收敛空间，看detect图也会发现角度学习的也有一点偏差。
那就接着权重继续训练吧，大参数模型在较强的数据增强trick作用下训练时间长一点有利于提升泛化能力。
一些dota数据集上面的提点小技巧可以参考：https://zhuanlan.zhihu.com/p/422764914
