### ISSUE TITLE
可以用pytorch1.8 cuda11.1框架来训练模型吗？

### ISSUE THREAD

**Issue by yueyang07** [hukaixuan19970627/YOLOv5_DOTA_OBB#11]
## ❔Question

因为使用的是rtx30系列的显卡，已经升级到pytorch1.8 和cuda11.1，请问你的这个代码支持吗？如果要改的话，有哪些需要调整的？

**Comment by gengyanlei** [comment]
@yueyang07 pytorch1.8 这个项目不支持，报错。改动还是有点麻烦的。

**Comment by Uncolor-Duck** [comment]
测试成功，cuda11.1可以正常，torch采用的是1.9版本
