### ISSUE TITLE
在运行detect.py代码时遇到error

### ISSUE THREAD

**Issue by abc15933858032** [hukaixuan19970627/YOLOv5_DOTA_OBB#110]
## ❔Question
RuntimeError:cannot perform reductiom function max on tensor with no elements because the operation does not have an identity

## Additional contex
![QQ图片20211115191203](https://user-images.githubusercontent.com/79972592/141772352-d6b4c736-43fc-429c-848c-0738055acfff.jpg)
t

**Comment by hukaixuan19970627** [comment]
改动了哪里呢，正常情况下不会运行到这一行代码的。另外运行环境什么的打印一下看看

**Comment by abc15933858032** [comment]
好像没有进行自己的修改，按照流程下载示例放到了DOTA_demo_view里面，没有进行其他调整就报错了
pandas版本用的1.1.5（不知道这个会不会有影响）

**Comment by hukaixuan19970627** [comment]
那就是下错了权重文件，只有第一个是训练好的旋转检测器，其余均为coco预训练权重文件，只适用于水平检测
![image](https://user-images.githubusercontent.com/72599120/141781101-f7f4e8a8-d3f7-4c06-9932-b17bf48fbf8a.png)
