### ISSUE TITLE
关于模型大小的咨询

### ISSUE THREAD

**Issue by HeuristicLU** [hukaixuan19970627/YOLOv5_DOTA_OBB#111]
## ❔Question
你好，我在你的有个说明里面看到，你训练的yolov5_DOTA1.5_OBB是基于yolov5m模型的，但是我以这个或者以yolov5m.pt为预训练模型或者直接训yolov5m得到的模型大小都是128M，只有训练yolov5s的时候模型大小才44M，我想问下，您这边训练完后，还进行了什么处理了么？比如量化、剪枝之类的。或者我是哪里搞错了么？

**Comment by HeuristicLU** [comment]
我刚才仔细看了下代码，可能是没有训完，中间结果是128M，最后训完后模型是44MB

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/142201096-cdf64298-b5d9-47af-a336-c0d154bffbcd.png)
