### ISSUE TITLE
移动端部署

### ISSUE THREAD

**Issue by dongshaojia** [hukaixuan19970627/YOLOv5_DOTA_OBB#112]
## ❔Question
感谢您的工作，您有没有在移动端上成功部署呢，比如在安卓上，有没有一些建议或者参考。

**Comment by hukaixuan19970627** [comment]
我不会嗷，没接触过。不过只要原版yolov5能成功部署的话，yolov5_obb一样可以部署，毕竟只对detect最后一层的通道数进行了改变
