### ISSUE TITLE
训练速度很慢

### ISSUE THREAD

**Issue by Eazin-g** [hukaixuan19970627/YOLOv5_DOTA_OBB#113]
## ❔Question
你好，请问你的训练速度能达到多少呢？我的训练速度是1.02it/s
我训练了dota数据集中的两个类，batch_size=16，workers=8，单个GPU，每个epoch训练完需要六分多钟，请问为什么会这么慢呢？
这样算起来完成训练需要一天的时间。

**Comment by hukaixuan19970627** [comment]
训练速度看gpu型号和使用模型的大小，想快一点的话可以把train.py中的csl label置为false

**Comment by hukaixuan19970627** [comment]
还想提速的话可以在旋转框NMS处优化一下，因为用的是cpu版本的poly_iou，所以训练过程中数据会切换device，也会影响效率，改为gpu版本的poly_iou也能提速。
