### ISSUE TITLE
batch_size 和训练速度

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/YOLOv5_DOTA_OBB#114]
## ❔Question
1、我想请问这个空白的图片没有目标的图片需要加入一起训练吗？
2、我batch_size 一开始设4 workers =8  , 每个epoch 需要20分钟，训练时间特别久。我batch_size 调到了256 , workers调到16 我把图片resize 到512，（ DOTA v-1.5 我空白没有目标的图像也放在里面，所以图像很多），每在batch_size 调大以后时间还是很久。

**Comment by hukaixuan19970627** [comment]
1. 可以但没必要，没看过哪个实验结论说增加纯背景样本可以提高精度的
2. Circular Smooth Label计算量稍微大一点，关闭的话可以提高训练速度，在train.py中全局搜索csl_flag置为False就行。

**Comment by NjustWrunning** [comment]
好的十分感谢
