### ISSUE TITLE
obj_loss问题

### ISSUE THREAD

**Issue by 1127244933** [hukaixuan19970627/YOLOv5_DOTA_OBB#115]
obj_loss总是会在十几轮的时候突然飘起来。数据集大概3000多图片，都是1024*1024大小。冻结层数和不冻结都尝试过，也没有改观。看看什么情况。中途obj_loss升起来我直接就暂停了。
## Additional context
![train_batch0](https://user-images.githubusercontent.com/72912006/143827136-87fb95e
![train_batch1](https://user-images.githubusercontent.com/72912006/143827226-665e49c5-7f9f-41a8-852c-65e5f31e9088.jpg)
![train_batch2](https://user-images.githubusercontent.com/72912006/143827242-d56bfb56-b4eb-47ec-93da-3af8eea6936a.jpg)
7-1bff-4863-ba92-4a170f1a8b65.jpg)
![Uploading Screenshot from 2021-11-29 15-34-43.png…]()

**Comment by NjustWrunning** [comment]
你好，你这是什么数据集，可以共享一下吗

**Comment by hukaixuan19970627** [comment]
你nc置为2再训练试试看，调低cls loss的权重，调高obj loss的权重

**Comment by 1127244933** [comment]
> 
nc设置为2了，cls loss权重和obj loss权重在那个文件里设置呀

**Comment by hukaixuan19970627** [comment]
@1127244933  data/下的yaml文件为超参数配置文件
