### ISSUE TITLE
backbone

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/YOLOv5_DOTA_OBB#116]
## ❔Question
当前代码使用的backbone 是什么？可以替换吗，我看了一下代码，不知道该怎么改

**Comment by hukaixuan19970627** [comment]
1. CSPDarkNet；
2. 可以替换，models/下的yaml文件就是不同参数量的检测器的配置文件，可以自行更改基础组件。如果想新增backbone，在models/common.py中新增小组件的类就可以了。
