### ISSUE TITLE
训练出错

### ISSUE THREAD

**Issue by devil1213** [hukaixuan19970627/YOLOv5_DOTA_OBB#117]
## ❔Question
你好，我这边按照你的上一个代码分割，转换了DOTA数据集的格式成yolo格式，但是我在训练模型的时候出现了下面的错误提示：train: WARNING: Ignoring corrupted image and/or label 
请问在你训练的时候出现了吗 谢谢

**Comment by hukaixuan19970627** [comment]
是你自己的数据集吗，dota数据集的话按readme安装环境以及操作的话不应该报错的。
另外这个错误搜索引擎可以直接搜索得到，你可以对照一下

**Comment by devil1213** [comment]
好的 感谢大佬 我好像用的是官方的权重文件好像是水平框的 是要下你提供的旋转权重文件吧

**Comment by devil1213** [comment]
十分感谢大佬的工作

**Comment by hukaixuan19970627** [comment]
OBB - Oriented Bounding Box，带obb的是基于dota的旋转检测器的权重，其余均为原版yolov5基于coco的预训练权重。
