### ISSUE TITLE
检测框问题

### ISSUE THREAD

**Issue by wubalahao** [hukaixuan19970627/YOLOv5_DOTA_OBB#118]
博主你好
我用了你的方案做了一个单目标的检测
但是现在有两个问题：1是大目标船容易漏检和检测框偏移，2是容易出现多个检测框，我想问一下原因是不是我的数据集不够或者是其他的，求教一下不胜感激[笑哭]
![image](https://user-images.githubusercontent.com/65750931/143880311-b451db1d-d875-4626-8e0b-1833d472d81e.png)

**Comment by hukaixuan19970627** [comment]
数据集的情况，配置文件的修改情况，trainbatch0/1/2，loss曲线图，detect可视化图等都发一下

**Comment by wubalahao** [comment]
![300轮效果](https://user-images.githubusercontent.com/65750931/144024463-9cd71c94-8de4-4472-a3c4-9b2d5b8e1f4c.jpg)
![1 (37)](https://user-images.githubusercontent.com/65750931/144024539-eff592ce-ef11-4cb8-a55f-bd0fe0c96062.jpg)
以上是detect的结果。
![200轮results](https://user-images.githubusercontent.com/65750931/144024619-09de7d33-8bdc-47ca-99a9-fc9bf25ef304.png)
![300轮results](https://user-images.githubusercontent.com/65750931/144024639-e6df1d3e-b96d-4975-8d1f-e41412a32ee3.png)
以上是训练结果
![train_batch0](https://user-images.githubusercontent.com/65750931/144024684-8d353208-3eae-4708-adc3-2c6f8ce60857.jpg)
以上是batch0
![image](https://user-images.githubusercontent.com/65750931/144024745-6a5f2fb8-4095-46aa-97bb-9aa11cd01809.png)

以上是label格式
![image](https://user-images.githubusercontent.com/65750931/144024854-bf2993e3-d2c6-4bd2-8b3a-8b97871557d2.png)
这是标注的框

**Comment by wubalahao** [comment]
数据集大概80张图，每张里面有20条船左右

**Comment by hukaixuan19970627** [comment]
1. trainbatch0/1/2为数据增强后，即将进行前向传播的label的可视化结果，这说明你转换的label是有问题的，再检查一下吧。
2. loss曲线图说明网络还远远没到收敛的时候。

**Comment by wubalahao** [comment]
好的谢谢作者大大，肥肠感谢

**Comment by wubalahao** [comment]
作者你好，我把输入的图像pad成了正方形，问题得到了解决。但是现在出现了新的问题，就是对小目标的检测效果还好，但是对大船的检测会当成好多小船，请问一下这可能是那些原因导致的

**Comment by wubalahao** [comment]
![image](https://user-images.githubusercontent.com/65750931/144718317-71923216-f976-4cf1-b247-92b8e4a9341b.png)

**Comment by wubalahao** [comment]
![image](https://user-images.githubusercontent.com/65750931/144718326-c3a004fe-4f8c-4b3a-87df-990882a26f42.png)

**Comment by hukaixuan19970627** [comment]
数据集规模，配置文件的修改情况，trainbatch0/1/2，loss曲线图，detect可视化图等再发一下。
每次重新训练后的信息给全一点，方便定位问题。

**Comment by wubalahao** [comment]
数据集规模是120张1024*720和上次一样每张图有20左右条船，近处的大船比较少，远处的小船比较多，然后配置文件如下：
![image](https://user-images.githubusercontent.com/65750931/144749651-ef8892bb-d859-4408-b1a5-3dc4a0eec6b6.png)
![image](https://user-images.githubusercontent.com/65750931/144749664-4241bc57-6107-4daa-a710-2d731d0fcff2.png)
![image](https://user-images.githubusercontent.com/65750931/144749696-8193f5e9-89e4-47f4-bd85-c000416cd606.png)
![image](https://user-images.githubusercontent.com/65750931/144749699-172497ee-632a-4d0a-8277-2ca0bac40ba1.png)
![image](https://user-images.githubusercontent.com/65750931/144749704-00b9b889-23a2-4ccb-ace3-348b1277382f.png)
detect结果，每次遇到大船都会被识别为多艘小船：
![image](https://user-images.githubusercontent.com/65750931/144749722-84cc386d-5cbd-493b-9779-801810e3d899.png)
![image](https://user-images.githubusercontent.com/65750931/144749746-000fb91c-9dcd-46be-82dd-538d6cf6478f.png)

**Comment by wubalahao** [comment]
是不是我大船的数据比较少，我是不是应该把大船单独分为一类去检测呢大佬。
再次感谢大佬的耐心指导！！

**Comment by hukaixuan19970627** [comment]
之前不提到了两点么，第二点你还没解决呢，loss曲线图很明显，网络还没收敛。

**Comment by liangbaqiang** [comment]
@wubalahao ,请问解决了吗，我也遇到这个问题了

**Comment by wubalahao** [comment]
> @wubalahao ,请问解决了吗，我也遇到这个问题了

更换yolo5m模型训练后loss可以收敛了但是大目标还是存在多检测的问题。。大哥如果有路子解决带我一下哈

**Comment by hukaixuan19970627** [comment]
@wubalahao 
如果在开启mosaic的前提下loss曲线收敛的差不多了，那么可以接着此时的权重进行训练，这个时候关闭mosaic，mixup等多样本数据增强，接着训练一段时间看看效果，比如训练了150epoch，那么最后再关闭多样本数据增强继续训练15epoch，性能会有所提升。多样本数据增强后的数据分布和原始数据是不一样的，前者可确保较优的收敛方向，后者直接拟合原始数据集的能力更强。

**Comment by hukaixuan19970627** [comment]
不追求部署，只追求精度的话可以看看别的检测算法。
https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA

**Comment by sjx3906** [comment]
> 作者你好，我把输入的图像pad成了正方形，问题得到了解决。但是现在出现了新的问题，就是对小目标的检测效果还好，但是对大船的检测会当成好多小船，请问一下这可能是那些原因导致的

请问你是如何pad成正方形的呢，为什么这样能解决多框跟识别框倾斜的问题呢

**Comment by wubalahao** [comment]
> > 作者你好，我把输入的图像pad成了正方形，问题得到了解决。但是现在出现了新的问题，就是对小目标的检测效果还好，但是对大船的检测会当成好多小船，请问一下这可能是那些原因导致的
> 
> 请问你是如何pad成正方形的呢，为什么这样能解决多框跟识别框倾斜的问题呢

这个是很久之前的问题了，当时应该就是作者的dataloder没有写好自适应的输入，现在他的新版本应该早就不存在这个问题了，我也好久没有研究这个方向了..

**Comment by sjx3906** [comment]
> > > 作者你好，我把输入的图像pad成了正方形，问题得到了解决。但是现在出现了新的问题，就是对小目标的检测效果还好，但是对大船的检测会当成好多小船，请问一下这可能是那些原因导致的
> > 
> > 
> > 请问你是如何pad成正方形的呢，为什么这样能解决多框跟识别框倾斜的问题呢
> 
> 这个是很久之前的问题了，当时应该就是作者的dataloder没有写好自适应的输入，现在他的新版本应该早就不存在这个问题了，我也好久没有研究这个方向了..

好的好的，谢谢您
