### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/YOLOv5_DOTA_OBB#119]
## ❔Question
您好大佬，我想问一下，为什么在开始训练之前会有这个错，我按照你之前那个dota_devkit_yolo弄了旋转框的标注，是因为obb的标注里面有6栏，而yolov5原版代码里只有5栏参数嘛，那代码里还需要改哪里呢，
![image](https://user-images.githubusercontent.com/64736467/143973104-80d1c9dc-1a97-4cec-b8c1-2a081c8f128d.png)

**Comment by shenhaibb** [comment]
![image](https://user-images.githubusercontent.com/64736467/143974876-7c35841e-ee91-4248-9a2f-cc2063e488bb.png)
这是我的注释文件 。。

**Comment by devil1213** [comment]
我也是这个问题 我之前以为是用的HBB的权重文件出的错误 现在我用OBB权重文件也还是出现这个错误 我不知道哪里出了问题 老哥解决了说一哈

**Comment by hukaixuan19970627** [comment]
demo全都能运行成功吗，readme里面我提供了demo所需的测试文件，如果demo全都能跑通说明转换数据集的时候有哪个步骤出了错

**Comment by shenhaibb** [comment]
> demo全都能运行成功吗，readme里面我提供了demo所需的测试文件，如果demo全都能跑通说明转换数据集的时候有哪个步骤出了错

就是我现在用的是u版的代码 ，没有用到您发布的这个项目——YOLOv5_DOTA_OBB，然后我转换数据集的时候用的是您另一个github的项目——DOTA_devkit_YOLO
先试运行了ImgSplit.py，然后运行了YOLO_Transform.py，运行Draw_DOTA_YOLO.py之后也可以画出框框
想问下这个是不是得用您发布的YOLOv5_DOTA_OBB

**Comment by devil1213** [comment]
我弄好了 要用大佬的yolov5代码 用原始代码会报错

**Comment by shenhaibb** [comment]
> 我弄好了 要用大佬的yolov5代码 用原始代码会报错

好吧

**Comment by hukaixuan19970627** [comment]
...没懂，你是想自己把yolov5-hbb改成yolov5-obb吗，如果是这样的话，除了backbone和neck部分其余涉及到数据通道的函数全都要修改，包括数据增强，数据载入等函数，自己修改的话一步步debug找错误吧。
要对照我的项目进行新版yolov5修改的话，也可以参考我这个项目，这个项目是基于2020年10月11日的yolov5进行修改的，你可以下载那个时间节点的yolov5进行对照，然后在最新版的yolov5中进行改建。

**Comment by shenhaibb** [comment]
> 

好的谢谢楼主^ ^
