### ISSUE TITLE
No access to Baidu files

### ISSUE THREAD

**Issue by csouflis** [hukaixuan19970627/YOLOv5_DOTA_OBB#12]
Hello,

Thanks for making your repo available to github community. Is it possible for you to put the demo files and trained YOLO model on google drive or dropbox because some of us don't have access to Baidu Cloud outside of China.

Thanks.

**Comment by hukaixuan19970627** [comment]
I'm uploading files to Google Drive. It may take half an hour.

**Comment by csouflis** [comment]
I see the updated README with the GoogleDrive links.

Thank you!
