### ISSUE TITLE
detect.py检测不出问题

### ISSUE THREAD

**Issue by Banyue-1** [hukaixuan19970627/YOLOv5_DOTA_OBB#120]
## ❔Question
大佬你好，我在用您的代码训练我自己的数据集，图片大小为2048×2048，训练时未切割，可以用train.py完成训练，但是无法用detect.py检测出目标。原始图片和标注的label如下：

![000045](https://user-images.githubusercontent.com/76894871/144393294-66309d79-3240-43e3-bde1-8cbb60f7dcbe.jpg)

![$OIB9R9@}0`WZ 9W X$Q I1](https://user-images.githubusercontent.com/76894871/144393450-f85a49a9-a2c3-4c4e-bd48-1f366e6f48d5.png)

训练过程中修改了路径和类别ns和names，产生的train_batch图片如下：
batch0:
![train_batch0](https://user-images.githubusercontent.com/76894871/144394081-029698cd-18b5-4ce6-bd12-c53e31a97f3a.jpg)

batch1:
![train_batch1](https://user-images.githubusercontent.com/76894871/144394155-dc1d30ed-5a47-4ad5-a4f2-743ca7972bfc.jpg)

batch2:
![train_batch2](https://user-images.githubusercontent.com/76894871/144394211-7874a353-65ce-4adb-9ab7-11e8e7ba1f32.jpg)

感觉train_batch中的标注是对的，虽然被切割了。

train.py中修改的路径：
![Y5`@7CMAA$QX$T AOG WDL5](https://user-images.githubusercontent.com/76894871/144394402-65cc4767-a671-4d22-909a-3c3231470822.png)

谢谢大佬！

**Comment by hukaixuan19970627** [comment]
你的数据集规模有多大呢？还有训练完后的loss曲线最好也发一下

**Comment by Banyue-1** [comment]
> 

数据集只有40张图片，而且因为直接用CPU跑的，只跑了20次。

![results](https://user-images.githubusercontent.com/76894871/144603239-067eec89-561e-4808-b749-c4501bdc7491.png)

是因为还没有收敛吗？CPU跑太难了(叹气)
还是因为没有切割图片，导致训练出来的网络无法检测一整张图片呀？

谢谢大佬。

**Comment by hukaixuan19970627** [comment]
这loss曲线不是很明显嘛，离收敛还远着呢。40张图片，20个epoch，哪怕batchsize为1，这网络结构也只迭代了800次。
另外你这又不需要检测小目标，那就没必要原图size输入网络，缩放为1024甚至更小也可以满足需求

**Comment by Banyue-1** [comment]
Okk，谢谢大佬。还是搞张显卡再玩吧hh

**Comment by lzfshub** [comment]
哥们，你好，请问你的数据集如何制作的，可以留个联系方式，问一下吗，感谢！！！！！！！

**Comment by Banyue-1** [comment]
用的roLabelImg
