### ISSUE TITLE
大佬，检测HRSC2016数据集时，train0/1/2都比较准确，但detect.py连框都没有是什么原因啊

### ISSUE THREAD

**Issue by yanxioa** [hukaixuan19970627/YOLOv5_DOTA_OBB#121]
## ❔Question
![图片](https://user-images.githubusercontent.com/58209569/145176715-440f6c8b-6764-427c-a22f-35947e755a81.png)
![图片](https://user-images.githubusercontent.com/58209569/145176853-36a65e53-c5b9-404e-9586-177e38511ace.png)

**Comment by hukaixuan19970627** [comment]
train0/1/2是可视化数据增强后的图像label，视觉上框的角度不怎么准确，是不是图像宽高不一致呢？这个项目暂时不支持宽高不一致的图像。
另外detect检测不出来，你可以尝试调低一下置信度。loss收敛到这个程度不至于什么都检测不出来
