### ISSUE TITLE
关于DOTA-v15中 Test 数据集在Task1任务的精度问题！

### ISSUE THREAD

**Issue by stevenXS** [hukaixuan19970627/YOLOv5_DOTA_OBB#122]
## Question
作者您好，我提交了检测结果TXT文件到DOTA官方网站在线评估，其结果如下
mAP：62.8左右，请问这个精度是正常的吗？

## Additional context

![image](https://user-images.githubusercontent.com/53604654/145530062-96946b61-7974-4daf-81cd-e1d9ec98a74b.png)

detect的参数设置：

- image-size：800
- iou-thres：0.5
- conf-thres: 0.1
- agnostic-nms: False

切割参数设置：

- gap-200, size-1024

**Comment by hukaixuan19970627** [comment]
我记得你当时不是问过一次了么，#90。
Benchmark 做mAP评测时设置都是 inference-image-size 1024，conf-thres=0.05/0.01，gap-200, subsize-1024.
