### ISSUE TITLE
四个不同的pretrain_model

### ISSUE THREAD

**Issue by NjustWrunning** [hukaixuan19970627/YOLOv5_DOTA_OBB#123]
## ❔Question
四个不同的pretrain_model：
yolov5m.pth
yolov5l.pth
yolov5x.pth
yolov5s.pth
这四个pretrain 对应model中的四个网络结构文件yolov5m.yaml yolov5l.yaml yolov5x.yaml yolov5s.yaml，我知道这四个网络结构文件参数设置 有什么区别 是针对某些特殊的场景还是什么 我想知道这些参数的意义 anchors应该是多尺度的下采样大小，但是depth_multiple 这些设置 应该是对应某些场景下会比较好，比如是针对小目标 还是目标聚集等问题的
![image](https://user-images.githubusercontent.com/73689702/146112704-35f7fb2e-3f33-4f56-8949-72855c2d93c2.png)
![image](https://user-images.githubusercontent.com/73689702/146112728-5d1f3d2f-ca7e-4756-8c64-a485e065cb40.png)

**Comment by hukaixuan19970627** [comment]
就是大参数模型和小参数模型的配置文件。depth width用于控制卷积网络的层数（深度）和通道数（宽度）。
相当于ResNet18 ResNet50 ResNet101 ResNet152之间的区别一样，只不过yolov5可以通过参数的设置，直接完成结构的切换，工程应用比较方便而已。
使用场景的话看性能速度需求选择合适的模型，一般实时场景就只考虑yolov5m及其以下的模型就可以了
