### ISSUE TITLE
map不正常

### ISSUE THREAD

**Issue by shenhaibb** [hukaixuan19970627/YOLOv5_DOTA_OBB#127]
## ❔Question
我的输入图片大小是640*640 训练了90epoch，map只有18
我用的数据集是dota1.0 yolov5s
![image](https://user-images.githubusercontent.com/64736467/146478542-c76bd4cc-2b2c-4483-b899-87a5b323d2e8.png)

这是我的train012
![train_batch0](https://user-images.githubusercontent.com/64736467/146474779-948339bc-a08c-40a0-9b82-9f72fa40504f.jpg)
![train_batch1](https://user-images.githubusercontent.com/64736467/146474786-19ad3458-2748-4daa-b163-5e69ac981ed9.jpg)
![train_batch2](https://user-images.githubusercontent.com/64736467/146474790-511cf835-0e15-4b15-9883-4ae7505e63e7.jpg)

会和输入图像大小有关吗 不能是640 必须是1024之类的
## Additional context
![image](https://user-images.githubusercontent.com/64736467/146474820-efd30be1-a5a4-4dea-994c-ad122601d232.png)

**Comment by hukaixuan19970627** [comment]
dota数据集的benchmark，前提是数据集要经过切割，切割参数为subsize=1024，gap=200

**Comment by shenhaibb** [comment]
> 

是用了您的代码切割了的 我输入图片大小为640是训练的时候大小是640 1024电脑跑不太起来 我想问的是 和训练的时候输入图片大小会有关系吗

**Comment by hukaixuan19970627** [comment]
测试的时候切割了吗

**Comment by shenhaibb** [comment]
> 测试的时候切割了吗

![image](https://user-images.githubusercontent.com/64736467/146508625-b721fb68-967b-443d-9569-1f966771bbab.png)
测试的时候用的数据集中的val里面的图片 也是切割了的 train里的图片咋切 val里的图片也是咋切的 是要用test文件夹里的图片吗 我看test里面没有标注文件我就没有用 用的是val的

**Comment by shenhaibb** [comment]
会和置信度 iou阈值有关系吗 那个参数我没有变过

**Comment by hukaixuan19970627** [comment]
你是切的1024，然后用640训练的吗

**Comment by shenhaibb** [comment]
> 你是切的1024，然后用640训练的吗

对的对的 我现在用1024训练一下试试

**Comment by hukaixuan19970627** [comment]
resize是会丢失图像信息的，对小目标检测影响会比较大。
不过你测试的时候用1024来测试的话，map会比你现在的高很多

**Comment by shenhaibb** [comment]
意思是 训练的时候可以用640 但是检测的时候用1024吗

**Comment by hukaixuan19970627** [comment]
我的意思是大尺度size测试可以提点。
高分辨率图像检测中尽量不要使用resize来缩小图像，因为会造成部分细节信息的丢失，你实在是显存不够的话，那你就切成512x512呗，用512分辨率来训练测试呗

**Comment by shenhaibb** [comment]
> 

好嘞我去试试 谢谢大佬

**Comment by shenhaibb** [comment]
> 我的意思是大尺度size测试可以提点。 高分辨率图像检测中尽量不要使用resize来缩小图像，因为会造成部分细节信息的丢失，你实在是显存不够的话，那你就切成512x512呗，用512分辨率来训练测试呗

512和640训练的时候不一样吗 有啥差别呀。。。

**Comment by shenhaibb** [comment]
博主大佬 我用1024跑了一下精度还是可低 只有26点多 我想问一下那个detect.py里conf-thres是0.25，iou-thres是0.4 这个是从您github上直接拉下来的代码 但是我看到您有一篇知乎上的https://zhuanlan.zhihu.com/p/357992219，设置的是conf_thresh=0.05, IoU_thresh=0.1，会和这个有关系吗
或者会不会因为我用的数据集是dota1.0的 您代码里的evalute是1.5的 我要用dota_devkit那个代码里使用那个针对dota1.0的evalute呢

**Comment by hukaixuan19970627** [comment]
> 博主大佬 我用1024跑了一下精度还是可低 只有26点多 我想问一下那个detect.py里conf-thres是0.25，iou-thres是0.4 这个是从您github上直接拉下来的代码 但是我看到您有一篇知乎上的[https://zhuanlan.zhihu.com/p/357992219，设置的是conf_thresh=0.05](https://zhuanlan.zhihu.com/p/357992219%EF%BC%8C%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%98%AFconf_thresh=0.05), IoU_thresh=0.1，会和这个有关系吗 或者会不会因为我用的数据集是dota1.0的 您代码里的evalute是1.5的 我要用dota_devkit那个代码里使用那个针对dota1.0的evalute呢

你是用的readme里面的权重去测试dotav1吗？那不行的，权重是用的dotav1.5训练的，v1.5和v1.0图片完全一致，就是新增了一个类以及新增了很多小目标（甚至<10x10），所以后者训练的权重测1.0是不行的，因为很多极小物体在dotav1中是背景，会降低mAP。
另外一般来说conf-thres越低，测试得到的mAP就会越高

**Comment by shenhaibb** [comment]
我不是用您readme里的权重去测试的。我是自己跑了一个
我按照1024跑了一遍 模型这次不用5s了 用的5m 数据集也不用dota1.0 用dota1.5 跑到50代的时候map为32多 现在跑到60代了 我发现loss好像下不去了 
![image](https://user-images.githubusercontent.com/64736467/147404669-b254f915-10f3-456a-ae4a-8b4ba5ed3aec.png)
所有参数都和你设置的一样 为啥结果差这么多呢
train012
![image](https://user-images.githubusercontent.com/64736467/147404698-d5b5bcdc-1b52-483e-a8cd-f402daa1fa42.png)
![image](https://user-images.githubusercontent.com/64736467/147404701-efab2a3f-2fc7-4c64-9e12-a5ac5f23d6b1.png)
![image](https://user-images.githubusercontent.com/64736467/147404706-299ac872-487d-4229-b37a-20fcb8b3f8f9.png)
这个是loss
![image](https://user-images.githubusercontent.com/64736467/147404710-3691d1be-8aa7-4b14-ae31-bde4cc395e58.png)

**Comment by hukaixuan19970627** [comment]
emmm，我是训了150epoch的。
精度是可以复现的，不知道是不是你哪里没设置好，可以参考这个issue，#58
不追求部署，追求精度的话可以试试这个[repo](https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA), 整体训练时间会比yolov5这个要快得多，只需36epoch就有SOTA的精度。
我这两周会更一版全新的yolov5-obb，这一版代码功能缺失的有点多，代码结构也不好，而且这个代码是我入门那会儿改建的，for循环太多，cuda cpu设备之间来回传输数据的操作太多，所以训练效率很低，我自己都嫌训练时间长所以都不咋用这个版本。不急的话可以等等，

**Comment by shenhaibb** [comment]
> 

我知道大佬您的代码肯定能复现 一点都没有怀疑你的意思 我也一直在找原因 已经跑了好久了都跑不出来 可把我愁死了 我会把150个epoch都跑完看看的 谢谢大佬！

**Comment by hukaixuan19970627** [comment]
验证代码自己加的吗，那其实你可以把CSL代码也给改了，训练速度会加快很多。这版csl是tensor转array后再进行高斯处理，然后再转tensor，没必要，你直接把np对应的操作都改成torch的函数，显存利用率会高很多

**Comment by shenhaibb** [comment]
> 验证代码自己加的吗，那其实你可以把CSL代码也给改了，训练速度会加快很多。这版csl是tensor转array后再进行高斯处理，然后再转tensor，没必要，你直接把np对应的操作都改成torch的函数，显存利用率会高很多

没有 就是下的您repo里的代码 啥也没改。。不太会改建代码 jiu gai le就改了cfg地址，还有数据集的地址。。。
![image](https://user-images.githubusercontent.com/64736467/147431220-91e3e9a9-22ad-4f82-ab82-8ebe470c7d35.png)
![image](https://user-images.githubusercontent.com/64736467/147431256-841f35b0-2683-46e9-ab35-75cf2aebf1f7.png)

**Comment by shenhaibb** [comment]
切割训练集和验证集图片我用的是ImgSplit_multi_process.py
测试集图片没有切割 因为还没用去dota官网里进行在线评估
![image](https://user-images.githubusercontent.com/64736467/147432423-3084bc3b-0361-4234-8d68-cbeb78fee02c.png)
切割完之后用YOLO_Transform.py进行转换，控制台里只出现这两类的数据 
那个：bbox[:2]中有>= 1的元素,bbox中有<= 0的元素,已将第17个box排除,问题出现在该图片中 这个是正常的情况吗
![image](https://user-images.githubusercontent.com/64736467/147432537-52dabb2a-6156-4049-bde1-c28452b0c176.png)

**Comment by hukaixuan19970627** [comment]
你拿readme里提供的权重去同样测试下看看

**Comment by shenhaibb** [comment]
> 你拿readme里提供的权重去同样测试下看看
![image](https://user-images.githubusercontent.com/64736467/147441676-88a90dcc-d3b6-4344-9548-28378f841719.png)
看上去挺正常的 我训练出来怎么那样/wu l捂脸

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/147442037-3ee99884-bf8b-4844-91ab-73c3f66fb688.png)
把冻结关了。接着训

**Comment by shenhaibb** [comment]
> ![image](https://user-images.githubusercontent.com/72599120/147442037-3ee99884-bf8b-4844-91ab-73c3f66fb688.png) 把冻结关了。接着训

大佬您的意思是 因为您的代码是默认使用预训练权重 才冻结代码 
但我因为是从头开始训练 所以不能冻结代码 所以才导致的精度低的吗
我现在去试试 谢谢您！

**Comment by hukaixuan19970627** [comment]
不管用不用预训练权重，尽量别用freeze功能就行，它可以加快训练速度但对最终的检测精度没有正面影响。
train from scratch不能冻结层，否则被冻结层的参数不会随训练迭代而更新。

**Comment by shenhaibb** [comment]
> 不管用不用预训练权重，尽量别用freeze功能就行，它可以加快训练速度但对最终的检测精度没有正面影响。 train from scratch不能冻结层，否则被冻结层的参数不会随训练迭代而更新。

现在正常了 
![image](https://user-images.githubusercontent.com/64736467/147754200-89525037-b5ce-4065-9112-68aff6e848b9.png)
请问大佬改建的对应的是这一行对实验吗
![image](https://user-images.githubusercontent.com/64736467/147754248-37c58b86-adde-4e99-8deb-a63bfd33ae9c.png)
感觉做基线我跑的61.08有点低了 是不是要加点trick提升一下基线之类的
我用5s跑hbb的时候map基线都70了 61.08的话对比不了几个论文TAT

**Comment by shenhaibb** [comment]
> > 不管用不用预训练权重，尽量别用freeze功能就行，它可以加快训练速度但对最终的检测精度没有正面影响。 train from scratch不能冻结层，否则被冻结层的参数不会随训练迭代而更新。
> 
> 现在正常了 ![image](https://user-images.githubusercontent.com/64736467/147754200-89525037-b5ce-4065-9112-68aff6e848b9.png) 请问大佬改建的对应的是这一行对实验吗 ![image](https://user-images.githubusercontent.com/64736467/147754248-37c58b86-adde-4e99-8deb-a63bfd33ae9c.png) 感觉做基线我跑的61.08有点低了 是不是要加点trick提升一下基线之类的 我用5s跑hbb的时候map基线都70了 61.08的话对比不了几个论文TAT

就是加到最后一行那种

**Comment by shenhaibb** [comment]
![image](https://user-images.githubusercontent.com/64736467/147756011-fa91edc0-cb10-40af-a9ea-095ba01e210f.png)
然后加了--adam优化器
然后这改成了2
![image](https://user-images.githubusercontent.com/64736467/147756082-ece4499c-fbcd-4878-8a54-cde3493ad921.png)
这些就是您最后一行消融实验的参数吗

**Comment by shenhaibb** [comment]
> emmm，我是训了150epoch的。 精度是可以复现的，不知道是不是你哪里没设置好，可以参考这个issue，#58 不追求部署，追求精度的话可以试试这个[repo](https://github.com/hukaixuan19970627/OrientedRepPoints_DOTA), 整体训练时间会比yolov5这个要快得多，只需36epoch就有SOTA的精度。 我这两周会更一版全新的yolov5-obb，这一版代码功能缺失的有点多，代码结构也不好，而且这个代码是我入门那会儿改建的，for循环太多，cuda cpu设备之间来回传输数据的操作太多，所以训练效率很低，我自己都嫌训练时间长所以都不咋用这个版本。不急的话可以等等，

看了大佬分享的那个仓库了 精度的确很高 但是我现在已经把论文写好了 内容啥的也都确定了 但是当时做的hbb的 想着换成obb的 但是obb的基线我不知道是咋（可能我哪里参数没调好）和hbb的基线精度差得有点多 我在hbb上用的也是yolov5s 基线都已经跑到70了。。。。哭

**Comment by hukaixuan19970627** [comment]
hbb那个yolov5s是新版的吧，我这个代码是基于yolov5的2020年的某个版本改建的，不适合直接进行对比，不过下周我会更一个新版的代码。

**Comment by shenhaibb** [comment]
> 

好嘞 谢谢大佬！我会天天蹲的/笑cry

**Comment by shenhaibb** [comment]
![image](https://user-images.githubusercontent.com/64736467/147875133-c0d5012b-e08d-410d-a3da-12a890cd56f3.png)
结果正常了 谢谢大佬！
