### ISSUE TITLE
服务器跑不了demo

### ISSUE THREAD

**Issue by LUO77123** [hukaixuan19970627/YOLOv5_DOTA_OBB#129]
## ❔Question
1、配置_polyiou时，出现warning，但是也生成了build文件和_polyiou.cpython-39-x86_64-linux-gnu.so。
2、跑demo时候，报错。是环境没配好吗？
## Additional context
1、问题
building '_polyiou' extension
polyiou.cpp: In function ‘double intersectArea(Point, Point, Point, Point)’:
polyiou.cpp:88:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if(s1*s2==-1) res=-res;return res;
     ^~
polyiou.cpp:88:28: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     if(s1*s2==-1) res=-res;return res;
2、问题
freezing model.9.m.1.cv2.bn.weight
freezing model.9.m.1.cv2.bn.bias
Traceback (most recent call last):
  File "/home/C/LUOLIE/YOLOv5_DOTA_OBB-master/train.py", line 912, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/C/LUOLIE/YOLOv5_DOTA_OBB-master/train.py", line 320, in train
    dataloader, dataset = create_dataloader(train_path,
  File "/home/C/LUOLIE/YOLOv5_DOTA_OBB-master/utils/datasets.py", line 70, in create_dataloader
    dataset = LoadImagesAndLabels(path, imgsz, batch_size,
  File "/home/C/LUOLIE/YOLOv5_DOTA_OBB-master/utils/datasets.py", line 501, in __init__
    labels, shapes = zip(*[cache[x] for x in self.img_files])
  File "/home/C/LUOLIE/YOLOv5_DOTA_OBB-master/utils/datasets.py", line 501, in <listcomp>
    labels, shapes = zip(*[cache[x] for x in self.img_files])
KeyError: '/home/C/LL/YOLOv5_DOTA_OBB-master/DOTA_demo_view/images/P0003__1__0___0.png'

**Comment by hukaixuan19970627** [comment]
demo没跑通的话应该就是路径/坏境问题了。先检查下环境版本是否和readme一致，如果有要求版本号的包，那就一定要一致

**Comment by LUO77123** [comment]
主要是我本地是win，torch1.10，torchvision0.10，都是最新的，也跑通了，换到linux，torch1.9不行，今天试了一下，1.8还是不行，这是报这个错，明天就按您的配置来，谢谢大佬



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 中午11:00
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 服务器跑不了demo (Issue #129)




 
demo没跑通的话应该就是路径/坏境问题了。先检查下环境版本是否和readme一致，如果有要求版本号的包，那就一定要一致
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hukaixuan19970627** [comment]
下周会更一版新的，这个版本的代码使用问题太多，下周基本都会修复
