### ISSUE TITLE
角度预测

### ISSUE THREAD

**Issue by lzfshub** [hukaixuan19970627/YOLOv5_DOTA_OBB#130]
## ❔Question这个用在自己的数据集上训练，可以实时进行角度的预测吗，输出角度的信息，比如，把旋转角度发送给客户端，实时检测
，比如应用在姿态上

**Comment by lzfshub** [comment]
运行您的dem哦，最后无法输出map值，显示无法检测到目标
![image](https://user-images.githubusercontent.com/61589851/147810835-6fab3cfd-c391-4694-8514-f10bb1bd8654.png)
，这是什么原因呢

**Comment by hukaixuan19970627** [comment]
检测姿态有专门的关键点检测算法，没必要用这个代码。实时检测角度的话是可以做到的，不过这一版的gpu detect效率较低，下周会更新一下。
demo是有可视化结果的，detect.py生成的图发上来看一下，都按readme操作的话，至少demo不应该出现问题的

**Comment by lzfshub** [comment]
我不是检测姿态的，我是想基于您的代码，针对我的数据集，做一个机械臂抓取的数据集检测，需要角度的信息，在yolo的基础上加角度信息，实时传输给机械臂，便于抓取这样子，检测的类别也比较简单

**Comment by lzfshub** [comment]
![Uploading image.png…]()
这是大致效果

**Comment by lzfshub** [comment]
> 检测姿态有专门的关键点检测算法，没必要用这个代码。实时检测角度的话是可以做到的，不过这一版的gpu detect效率较低，下周会更新一下。 demo是有可视化结果的，detect.py生成的图发上来看一下，都按readme操作的话，至少demo不应该出现问
