### ISSUE TITLE
一个关于角度的疑问

### ISSUE THREAD

**Issue by HKVINS89757** [hukaixuan19970627/YOLOv5_DOTA_OBB#134]
## ❔Question
看数据的话，角度为1 和角度为179，基本再图像上是没区别的，但是表达程angle的数据值 其差距就是178，请问这样会不会造成角度的loss变的很大？“

**Comment by hukaixuan19970627** [comment]
这个是旋转检测中常见的边界loss不连续的问题，这个问题有很多解决方法。Circular Smooth Label是其中一种，这个repo用的就是CSL，你可以看看这篇文章
