### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by roberttorres67** [hukaixuan19970627/YOLOv5_DOTA_OBB#14]
using torch 1.8.0+cu102 torchvision0.9.0

Using CUDA device0 _CudaDeviceProperties(name='GeForce GTX 1080', total_memory=8116MB)

Namespace(adam=False, batch_size=4, bucket='', cache_images=False, cfg='', data='data/DOTA_ROTATED.yaml', device='0', epochs=150, evolve=False, global_rank=-1, hyp='data/hyp.scratch.yaml', image_weights=False, img_size=[1024, 1024], local_rank=-1, logdir='runs/', multi_scale=False, name='', noautoanchor=False, nosave=False, notest=True, rect=False, resume=False, single_cls=False, sync_bn=False, total_batch_size=4, weights='./weights/yolov5m.pt', workers=8, world_size=1)
Start Tensorboard with "tensorboard --logdir runs/", view at http://localhost:6006/
2021-04-17 05:40:37.084303: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Hyperparameters {'lr0': 0.01, 'lrf': 0.2, 'momentum': 0.937, 'weight_decay': 0.0005, 'warmup_epochs': 3.0, 'warmup_momentum': 0.8, 'warmup_bias_lr': 0.1, 'box': 0.1, 'cls': 0.5, 'cls_pw': 1.0, 'obj': 1.0, 'obj_pw': 1.0, 'angle': 0.8, 'angle_pw': 1.0, 'iou_t': 0.2, 'anchor_t': 4.0, 'fl_gamma': 2.0, 'hsv_h': 0.015, 'hsv_s': 0.7, 'hsv_v': 0.4, 'degrees': 0.0, 'translate': 0.1, 'scale': 0.5, 'shear': 0.0, 'perspective': 0.0, 'flipud': 0.5, 'fliplr': 0.5, 'mosaic': 1.0, 'mixup': 0.0}

                 from  n    params  module                                  arguments                     
  0                -1  1      5280  models.common.Focus                     [3, 48, 3]                    
  1                -1  1     41664  models.common.Conv                      [48, 96, 3, 2]                
  2                -1  1     67680  models.common.BottleneckCSP             [96, 96, 2]                   
  3                -1  1    166272  models.common.Conv                      [96, 192, 3, 2]               
  4                -1  1    639168  models.common.BottleneckCSP             [192, 192, 6]                 
Overriding model.yaml nc=80 with nc=16
  5                -1  1    664320  models.common.Conv                      [192, 384, 3, 2]              
  6                -1  1   2550144  models.common.BottleneckCSP             [384, 384, 6]                 
  7                -1  1   2655744  models.common.Conv                      [384, 768, 3, 2]              
  8                -1  1   1476864  models.common.SPP                       [768, 768, [5, 9, 13]]        
  9                -1  1   4283136  models.common.BottleneckCSP             [768, 768, 2, False]          
 10                -1  1    295680  models.common.Conv                      [768, 384, 1, 1]              
 11                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 12           [-1, 6]  1         0  models.common.Concat                    [1]                           
 13                -1  1   1219968  models.common.BottleneckCSP             [768, 384, 2, False]          
 14                -1  1     74112  models.common.Conv                      [384, 192, 1, 1]              
 15                -1  1         0  torch.nn.modules.upsampling.Upsample    [None, 2, 'nearest']          
 16           [-1, 4]  1         0  models.common.Concat                    [1]                           
 17                -1  1    305856  models.common.BottleneckCSP             [384, 192, 2, False]          
 18                -1  1    332160  models.common.Conv                      [192, 192, 3, 2]              
 19          [-1, 14]  1         0  models.common.Concat                    [1]                           
 20                -1  1   1072512  models.common.BottleneckCSP             [384, 384, 2, False]          
 21                -1  1   1327872  models.common.Conv                      [384, 384, 3, 2]              
 22          [-1, 10]  1         0  models.common.Concat                    [1]                           
 23                -1  1   4283136  models.common.BottleneckCSP             [768, 768, 2, False]          
 24      [17, 20, 23]  1    812241  models.yolo.Detect                      [16, [[10, 13, 16, 30, 33, 23], [30, 61, 62, 45, 59, 119], [116, 90, 156, 198, 373, 326]], [192, 384, 768]]
Traceback (most recent call last):
  File "/home/user1/projects/308/Yolo_OBB/YOLOv5_DOTA_OBB-master/train.py", line 724, in <module>
    train(hyp, opt, device, tb_writer)
  File "/home/user1/projects/308/Yolo_OBB/YOLOv5_DOTA_OBB-master/train.py", line 126, in train
    model = Model(opt.cfg or ckpt['model'].yaml, ch=3, nc=nc).to(device)  # create
  File "/home/user1/projects/308/Yolo_OBB/YOLOv5_DOTA_OBB-master/models/yolo.py", line 168, in __init__
    self._initialize_biases()  # only run once
  File "/home/user1/projects/308/Yolo_OBB/YOLOv5_DOTA_OBB-master/models/yolo.py", line 262, in _initialize_biases
    b[:, 4] += math.log(8 / (640 / s) ** 2)  # obj (8 objects per 640 image)
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

**Comment by hukaixuan19970627** [comment]
pip install -r requirements.txt.
Make sure the requirements version is consistent with "requirements.txt".

**Comment by roberttorres67** [comment]
> pip install -r requirements.txt.
> Make sure the requirements version is consistent with "requirements.txt".

Hello @hukaixuan19970627 
Thank you for your answer. I did what you said but it didn't work for me.
