### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by nhathoang0110** [hukaixuan19970627/YOLOv5_DOTA_OBB#16]
## ❔Question
I want to ask why when I use the detect.py file the speed is very fast, but the speed when I use the test.py file is very slow?

我想问为什么当我使用detect.py文件时速度非常快，但是当我使用test.py文件时速度却很慢？

**Comment by hukaixuan19970627** [comment]
‘test.py’ does not currently support the evaluation of rotating object detection.

You can try 'evaluation.py' to evaluate the model.
