### ISSUE TITLE
θ计算出现异常，当前数据为：574.5000000000000000, 277.2500000000000000, 99.3124618530273438, 24.0312232971191406, 78.1;超出opencv表示法的范围：[-90,0)

### ISSUE THREAD

**Issue by MaLongbang** [hukaixuan19970627/YOLOv5_DOTA_OBB#17]
## Additional context
Traceback (most recent call last):
  File "detect.py", line 253, in <module>
    detect()
  File "detect.py", line 156, in detect
    det[:, :5] = scale_labels(img.shape[2:], det[:, :5], im0.shape).round()
  File "/home/malb/doc5/YOLOv5_DOTA_OBB-master/utils/general.py", line 297, in scale_labels
    label[-1] = int(label[-1] + 180.5)  # range int[0,180] 四舍五入
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

classy 一直是 flase

**Comment by hukaixuan19970627** [comment]
demo运行都有问题的话，先检查一下环境版本是否与requirements.txt一致

**Comment by MaLongbang** [comment]
> demo运行都有问题的话，先检查一下环境版本是否与requirements.txt一致

谢谢您，解决了
还想请问一下那个，预测的时候还会调用  polyiou 吗

**Comment by hukaixuan19970627** [comment]
> > demo运行都有问题的话，先检查一下环境版本是否与requirements.txt一致
> 
> 谢谢您，解决了
> 还想请问一下那个，预测的时候还会调用 polyiou 吗

只要涉及到旋转IoU计算的，都会调用polyiou，detect中有NMS过程，自然会调用它的

**Comment by ly0303521** [comment]
> > demo运行都有问题的话，先检查一下环境版本是否与requirements.txt一致
> 
> 谢谢您，解决了 还想请问一下那个，预测的时候还会调用 polyiou 吗

请问当时是怎么解决的，我这里一模一样....
