### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by nhathoang0110** [hukaixuan19970627/YOLOv5_DOTA_OBB#18]
when I used the evalution file for evaluation, I changed the following path to mine:
    classnames=['product']
    classnames_inVal = ['0']
    evaluation(
        detoutput='image_eval',
imageset=r'/mnt/hdd10tb/Users/hoangnn/product/prj14_data_gen/DATA_26/GenProduct_Yolo_26_convert90_final/images/test/',annopath=r'/mnt/hdd10tb/Users/hoangnn/product/prj14_data_gen/DATA_26/GenProduct_Yolo_26_convert90_final/labels/test/{:s}.txt',
        classnames=classnames_inVal
    )
However, I have bugs related to not having a file:
FileNotFoundError: [Errno 2] No such file or directory: 'image_eval/result_txt/result_classname/Task1_0.txt'
I don't know what the folders: result_before_merge, result_merged, result_classname, result_txt are and I need to create them myself?

**Comment by hukaixuan19970627** [comment]
![3IP(9QQGRQL~CZ2)6E}WS0B](https://user-images.githubusercontent.com/72599120/115653104-230ad600-a361-11eb-9a87-bbba6e23d62e.png)
Run detect.py. Get ~/result_txt/result_before_merge 
![T099FL{~C4@Y05%(QUJ4~QQ](https://user-images.githubusercontent.com/72599120/115653109-269e5d00-a361-11eb-9223-576c9f987c76.png)
Run evaluation.py. Get ~/result_txt/result_classname  and ~/result_txt/result_merged. 
You better run the demo with demo_files first.

**Comment by nhathoang0110** [comment]
I ran successfully with the demo file. However for my data set it doesn't, it seems to evaluate only dota data?

**Comment by hukaixuan19970627** [comment]
classnames_inVal = ['product']
same as  ~/result_txt/result_classname

**Comment by nhathoang0110** [comment]
I see an example with the dota dataset, which is the merge of parts of the image, etc. (I haven't seen it clearly yet). When I applied my dataset it didn't work, my dataset just has images and file annotations

**Comment by hukaixuan19970627** [comment]
Can you show me the files in this path ——‘image_eval/result_txt/result_classname/’
For example：
![image](https://user-images.githubusercontent.com/72599120/115708453-98e36180-a3a2-11eb-9f79-04bd4a0c2920.png)

**Comment by nhathoang0110** [comment]
I have not yet run to generate such files
I think because your annotations in row_DOTA_labels are different from my annotations. 
![image](https://user-images.githubusercontent.com/55668910/115808800-2c557a80-a415-11eb-93f4-90eada26974e.png)
![image](https://user-images.githubusercontent.com/55668910/115809333-17c5b200-a416-11eb-9077-fde2f35936c9.png)
My annotations is yolo format as training dataset.

**Comment by nhathoang0110** [comment]
Do you think that's the reason why I can't evaluate

**Comment by hukaixuan19970627** [comment]
> Do you think that's the reason why I can't evaluate
Yes.
The evaluation.py works for DOTA_labels format: [x1 y1 x2 y2 x3 y3 'classname'  diffcult] .
You can get  ‘image_eval/result_txt/result_classname/Task1_classname.txt’  by runing  detect.py.

Train_dataset annotations for train.py: [classid  x_c  y_c  longside  shortside  θ_id]
Ground Truth annotations for evaluation.py:  [x1 y1 x2 y2 x3 y3 'classname'  diffcult]

**Comment by nhathoang0110** [comment]
what is x1,y1,x1,y2,x3,y3,x4,y4 and gsd in dota annotation ground truth?

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/115862052-3489d600-a466-11eb-8c64-632e0d073bbe.png)

https://captain-whu.github.io/DOTA/dataset.html

**Comment by nhathoang0110** [comment]
Hello. 
I reformatted the data according to your format. However, I still got the error and couldn't explain it. Can you help me?
My code in evaluate.py :
    classnames=['0']
    classnames_inVal = ['0']
    #
    evaluation(
        detoutput='image_eval',
     imageset=r'/mnt/hdd10tb/Users/hoangnn/product/prj14_data_gen/DATA_26/GenProduct_Yolo_26_convert90_final/images/test/',
        annopath=r'/mnt/hdd10tb/Users/hoangnn/product/prj14_data_gen/new_txt_formatdota/{:s}.txt',
        classnames=classnames_inVal
    )
![image](https://user-images.githubusercontent.com/55668910/116533647-d3517f00-a90b-11eb-9a17-91c6ec3a9f3f.png)

**Comment by nhathoang0110** [comment]
this is my bug : 
![image](https://user-images.githubusercontent.com/55668910/116537933-14985d80-a911-11eb-96a4-7aa51c33b933.png)

**Comment by hukaixuan19970627** [comment]
Run detect.py on your dataset, you will get  ××/detection/result_before_merge/×××.txt. For example:
![image](https://user-images.githubusercontent.com/72599120/116655363-8ded8a00-a9bd-11eb-9a36-fdc0de1a10fd.png)

So what's the data-format you get?
