### ISSUE TITLE
数据处理时的不同尺度可以提升效果，如图

### ISSUE THREAD

**Issue by gengyanlei** [hukaixuan19970627/YOLOv5_DOTA_OBB#19]
![image](https://user-images.githubusercontent.com/22360785/115669008-61f95580-a37a-11eb-8043-fad446e32bf8.png)

**Comment by gengyanlei** [comment]
conf阈值>=0.15
nms-iou阈值>=0.05

**Comment by hukaixuan19970627** [comment]
不错哎，我之后闲下来的话尝试一下。对哦，我知乎私聊你联系方式了，我们可以相互交流

**Comment by hukaixuan19970627** [comment]
yolov5里面有个在线的多尺度训练，我不知道经过我的改建之后还有没有效果，因为我没改这一块，如果trainbatch0/1/2没有出现bbox偏移的现象的话，说明依然有效，你可以尝试一下
![image](https://user-images.githubusercontent.com/72599120/115677827-768e1b80-a383-11eb-9ef4-5301d5417941.png)

**Comment by gengyanlei** [comment]
嗯，我知道yolov5有多尺度训练，以前用yolov3训练时采用多尺度，显存占用太大，然后训练有点慢，另外我不清楚你这里有没有改动代码，都还没有仔细看你的代码，想仔细看 还是算了，想最小代价的改动代码，逼不得已再看代码 修改，看了一部分了，都没看核心代码呢。
好的，我主动加你

**Comment by gengyanlei** [comment]
@hukaixuan19970627 没看到你的联系方式呢

**Comment by xuexihui** [comment]
@gengyanlei 请问rate在哪里设置的

**Comment by hukaixuan19970627** [comment]
> @gengyanlei 请问rate在哪里设置的

DOTA_devkit_YOLO[https://github.com/hukaixuan19970627/DOTA_devkit_YOLO]项目使用ImgSplit.py裁剪时通过设置split.splitdata()中的参数，就可以达到离线多尺度裁剪的作用。

**Comment by xuexihui** [comment]
> > @gengyanlei 请问rate在哪里设置的
> 
> DOTA_devkit_YOLO[https://github.com/hukaixuan19970627/DOTA_devkit_YOLO]项目使用ImgSplit.py裁剪时通过设置split.splitdata()中的参数，就可以达到离线多尺度裁剪的作用。

谢谢!
