### ISSUE TITLE
请问windows下能安装polyiou吗，自己老是失败！

### ISSUE THREAD

**Issue by chenwenhao99** [hukaixuan19970627/YOLOv5_DOTA_OBB#2]

**Comment by hukaixuan19970627** [comment]
不建议在windows上安装，建议在linux环境下安装

**Comment by chenwenhao99** [comment]
> 不建议在windows上安装，建议在linux环境下安装

感谢回复！我还有个疑问就是poly_nms_gpu这个文件夹需要像poly_iou一样安装吗

**Comment by hukaixuan19970627** [comment]
除了安装requirements.txt中的环境以外
还要拓展c++的python接口，这些ReadMe中都有写。
注意swig命令的操作路径要放在yolov5_DOTA_OBB\utils。
除此之外没有其他安装坏境要求了

**Comment by hukaixuan19970627** [comment]
如果能完整运行yolov5与DOTA_devkit，环境就不会有问题

**Comment by chenwenhao99** [comment]
> 如果能完整运行yolov5与DOTA_devkit，环境就不会有问题

感谢！

**Comment by polar99** [comment]
windows下安装windows版的swig即可编译
