### ISSUE TITLE
训练速度特别慢

### ISSUE THREAD

**Issue by dolortaste** [hukaixuan19970627/YOLOv5_DOTA_OBB#20]
## ❔Question
为什么训练速度特别慢？训练的时候感觉相比较正常的yolov5只是加了一个角度分类维度的预测，为什么训练速度差很多呢

**Comment by hukaixuan19970627** [comment]
旋转IoU的计算比较费时，因为没有用cuda进行加速。
你可以重新下载这个项目，我改了几行代码，训练速度会加快，但最后的精度相比原来的是否降低得等明天的测试结果

**Comment by dolortaste** [comment]
> 旋转IoU的计算比较费时，因为没有用cuda进行加速。
> 你可以重新下载这个项目，我改了几行代码，训练速度会加快，但最后的精度相比原来的是否降低得等明天的测试结果

我用的是最新代码，计算ciou的版本

**Comment by hukaixuan19970627** [comment]
我这边是1s/it

**Comment by dolortaste** [comment]
> > 旋转IoU的计算比较费时，因为没有用cuda进行加速。
> > 你可以重新下载这个项目，我改了几行代码，训练速度会加快，但最后的精度相比原来的是否降低得等明天的测试结果
> 
> 我用的是最新代码，计算ciou的版本
> ![image](https://user-images.githubusercontent.com/6359718/116055810-aacd4900-a6af-11eb-8ecb-bac89038fe7f.png)

发现是CSL特别耗时

**Comment by hukaixuan19970627** [comment]
我这边同学以及师弟的训练速度都没有问题，哪怕是最慢的那个代码版本也是3s/it，建议按照readme检查一下多GPU训练是不是使用的DP模式而不是DDP模式

**Comment by dolortaste** [comment]
> 我这边同学以及师弟的训练速度都没有问题，哪怕是最慢的那个代码版本也是3s/it，建议按照readme检查一下多GPU训练是不是使用的DP模式而不是DDP模式

![image](https://user-images.githubusercontent.com/6359718/116058025-ff71c380-a6b1-11eb-8311-cefd9fe5c07b.png)
我是单卡训练的，关掉这个变成1s/it了
