### ISSUE TITLE
box loss can not drop

### ISSUE THREAD

**Issue by sunny-sjj** [hukaixuan19970627/YOLOv5_DOTA_OBB#22]
## ❔Question
您好!我在HRSC2016数据集训练单类别的时候box loss在前几轮训练的时候能正常下降，但是后面box loss就开始上升，然后稳定在较高的水平无法下降。使用训练200轮的权重，然后detection的效果跟预期的一样效果很差，请问您遇到这类情况了吗？

## Additional context
![2021-05-06 17-55-56 的屏幕截图](https://user-images.githubusercontent.com/63103208/117282007-dcf05f00-ae96-11eb-9559-fb732aec9ba7.png)

**Comment by hukaixuan19970627** [comment]
原始的yolov5就不支持单类别的检测，因为损失函数的问题至少需要二分类，所以要么你就修改原来的损失函数使其支持单分类，要么在训练的时候将nc置为2
