### ISSUE TITLE
只支持正方形图像训练吗

### ISSUE THREAD

**Issue by Allenstin** [hukaixuan19970627/YOLOv5_DOTA_OBB#24]
我发现只有正方形图像输入训练，训练结果才正常。如果是矩形图像输入训练，train_batchxx.jpg显示的框就乱了。请问大佬，目前是只能训练正方形图像吗

**Comment by hukaixuan19970627** [comment]
不支持weight≠height的图像进行训练，由于确定了旋转框的定义法为：x y longside shortside θ，原始yolov5的数据增强处理中太多归一化处理，但是旋转框的longside shortside与图像的宽高没有严格的对应关系，所以一旦w h不相等，数据增强后的框就会出现偏移/变形现象。
你可以用DOTA_devkit[https://github.com/hukaixuan19970627/DOTA_devkit_YOLO]这个工具中的split.py对原始图像进行处理，原始图像太大则将其切割为多张长宽相等的图，图像太小不足以切割的工具会直接将其进行填充置长宽相等的图像

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/119099252-4d77ae00-ba49-11eb-8fe4-e02f2521af14.png)

**Comment by Allenstin** [comment]
好的，谢谢大佬的耐心解答
