### ISSUE TITLE
请问大佬，新的poly_iou计算方式是在GPU上计算吗

### ISSUE THREAD

**Issue by Allenstin** [hukaixuan19970627/YOLOv5_DOTA_OBB#25]
请问大佬可以把poly_iou的计算，在 GPU中实现吗？

**Comment by hukaixuan19970627** [comment]
超出能力范围，搞不定！目前已经换成poly_nms_cpu_fast版本了，NMS时间会大幅缩短，cuda版本的我想蹲个现成的直接拿过来用，自己改写暂时不好搞，一是不会写，二是没时间学

**Comment by Allenstin** [comment]
嗯嗯，期待大佬最新成果
