### ISSUE TITLE
评估代码问题

### ISSUE THREAD

**Issue by Allenstin** [hukaixuan19970627/YOLOv5_DOTA_OBB#26]
感觉大佬给的评估代码用起来有点繁琐。如果能直接用yolov5中test.py那种方式去计算map，感觉会简洁很多。

**Comment by hukaixuan19970627** [comment]
这个评估程序专门给DOTA数据集用的，流程如下：detect检测切割后的图像并将检测结果保存至result.txt，evaluation.py将其merge，再与原始DOTA 注释文件进行评估比对。
你想节省第一步，自己删减删减代码就行了呗，后期有时间会多加一个通用版本的评估程序

**Comment by Allenstin** [comment]
好的，谢谢

**Comment by Allenstin** [comment]
大佬，你说demo详情见release，可以release里面没有东西.
![image](https://user-images.githubusercontent.com/42668169/119114279-997e1f00-ba58-11eb-8a46-e88be43e279e.png)

**Comment by Allenstin** [comment]
然后就是我在研读大佬eval代码时，看到大佬的代码有个解析groundtruth的操作，这个我理解是对xml的解析。可是DOTA的groundtruth，我下载下来全是txt文件，没有大佬代码要求的xml文件。
![image](https://user-images.githubusercontent.com/42668169/119114812-11e4e000-ba59-11eb-8142-bc5fd5d34a60.png)
