### ISSUE TITLE
大佬我用测试数据还有我个人的数据训练都没有效果

### ISSUE THREAD

**Issue by beibei12315** [hukaixuan19970627/YOLOv5_DOTA_OBB#27]
## ❔Question
我star了也folk，诚心求助呀
## Additional context
环境：windows
用大佬训练好的weights （YOLOv5_DOTA_OBB.pt）测试标注很好，但在试验训练的代码时发现不收敛。
测试数据：直接用的是大佬demo的数据，执行python train.py 。 
batchsize 4
epoch 150 
训练得到的result文件长这样：
   100/149     4.24G    0.2301   0.01797   0.02276    0.3905    0.6614       158      1024         0         0         0         0         0         0         0         0
   101/149     4.24G    0.2307   0.01975    0.0227    0.3783    0.6514        66      1024         0         0         0         0         0         0         0         0
   102/149     4.24G    0.2304   0.01748   0.02173    0.3773    0.6469        32      1024         0         0         0         0         0         0         0         0
   103/149     4.24G    0.2284   0.01488   0.02366    0.3678    0.6347        71      1024         0         0         0         0         0         0         0         0
   104/149     4.24G    0.2327    0.0176   0.01982    0.3642    0.6343        95      1024         0         0         0         0         0         0         0         0
   105/149     4.24G    0.2303   0.02012   0.02213    0.3723    0.6449        51      1024         0         0         0         0         0         0         0         0
   106/149     4.24G    0.2372   0.01658   0.02031    0.3688    0.6429        18      1024         0         0         0         0         0         0         0         0
   107/149     4.24G    0.2356   0.01885   0.01716    0.3587    0.6303       139      1024         0         0         0         0         0         0         0         0

什么都没改，只是把代码跑通了但是没有效果。
另外我个人标注的数据用YOLOv5可以得到一定的效果，但是密集的房屋很多识别不到，想试试大佬的网络，但是也是学习不到特征。诚心求助。膜拜大佬。

**Comment by beibei12315** [comment]
感谢，我把训练次数调到999，bach-size到16，可以了，训练过程中后面那些数字全部为000000.谢谢大佬的代码

**Comment by hukaixuan19970627** [comment]
后面那些数据为0是正常现象嗷，那一块都是原始yolov5项目中的在线评估部分，但是原先的代码不适合旋转框的评估，修改又太麻烦，所以代码删掉了，因此为0是正常现象。之所以还保留了这些为0的数据是因为我后期还会加在线评估的代码

**Comment by beibei12315** [comment]
> 后面那些数据为0是正常现象嗷，那一块都是原始yolov5项目中的在线评估部分，但是原先的代码不适合旋转框的评估，修改又太麻烦，所以代码删掉了，因此为0是正常现象。之所以还保留了这些为0的数据是因为我后期还会加在线评估的代码

原来如此呀
