### ISSUE TITLE
希望能够基于gpu计算nms！

### ISSUE THREAD

**Issue by LinB203** [hukaixuan19970627/YOLOv5_DOTA_OBB#31]
不知道您有没有想法，或者有什么相关教程能够引路的哇？

**Comment by hukaixuan19970627** [comment]
这个旋转检测器其实不错的，不过是基于tensorflow版本的，里面有各种旋转IoU的计算，当然也包括gpu版本的
[yangxue0827/RotationDetection](https://github.com/yangxue0827/RotationDetection)
