### ISSUE TITLE
demofiles运行YOLOv5_DOTAv1.5_OBB.pt正常，运行yolov5x.pt报错

### ISSUE THREAD

**Issue by surefyyq** [hukaixuan19970627/YOLOv5_DOTA_OBB#32]
请问带佬，配置好环境后用主页下载的YOLOv5_DOTAv1.5_OBB.pt跑demofiles的detect.py，没有问题检测效果良好，但是用yolov5s.pt和yolov5m.pt运行就报错cannot perform reduction function max on tensor with no elements because the operation does not have an identity，请问这是哪里的问题呢？

**Comment by hukaixuan19970627** [comment]
yolov5s/m/l/x.pt是预训练模型，是改为旋转检测之前的原始权重，只能训练时使用，可以提高最终的精度
YOLOv5_DOTAv1.5_OBB是改为旋转检测之后用yolov5m.pt预训练得到的最终权重，因此可以通用

**Comment by surefyyq** [comment]
明白了，感谢！

我正在尝试将贵工程在NVIDIA jetson设备（arm64 Ubuntu18.04）上运行于另一种旋转检测数据集，成功之后我会将整个流程分享给大家

**Comment by genfiewoul** [comment]
> 请问带佬，配置好环境后用主页下载的YOLOv5_DOTAv1.5_OBB.pt跑demofiles的detect.py，没有问题检测效果良好，但是用yolov5s.pt和yolov5m.pt运行就报错cannot perform reduction function max on tensor with no elements because the operation does not have an identity，请问这是哪里的问题呢？

您好！请问您这边还保留有YOLOv5_DOTAv1.5_OBB.pt的文件吗？原博主那已经取消分享了，想知道您是否愿意分享一份给我，如果愿意的话麻烦发一份到邮箱：1173299565@qq.com  ，不胜感激！祝您生活愉快！！
