### ISSUE TITLE
最后模型预测的pred有负数

### ISSUE THREAD

**Issue by zhaowendao30** [hukaixuan19970627/YOLOv5_DOTA_OBB#33]
## Additional context
[](url)
![图片](https://user-images.githubusercontent.com/49309820/121300891-fe2aec00-c929-11eb-81be-2a03fc5905da.png)

**Comment by hukaixuan19970627** [comment]
预测的输出格式是(x_center y_center longside shortside θ)，但为了方便可视化会转为四点坐标poly的形式，当预测的物体中心处于图像的左边界附近的时候，四点坐标有负数的情况就容易出现，但网络的预测结果是不会出现负数的，这个并不影响可视化的效果。
就好比一个篮球，被截的只剩一半，yolo这个网络会偏向于预测完整的物体，此时物体中心在图像内，但边框可能会超出图像外，我个人认为这个挺符合视觉常识的，如果你有特殊需求的话，可以限制四点坐标数值的最大最小值来规避这个现象

**Comment by zhaowendao30** [comment]
> 
> 
> 预测的输出格式是(x_center y_center longside shortside θ)，但为了方便可视化会转为四点坐标poly的形式，当预测的物体中心处于图像的左边界附近的时候，四点坐标有负数的情况就容易出现，但网络的预测结果是不会出现负数的，这个并不影响可视化的效果。
> 就好比一个篮球，被截的只剩一半，yolo这个网络会偏向于预测完整的物体，此时物体中心在图像内，但边框可能会超出图像外，我个人认为这个挺符合视觉常识的，如果你有特殊需求的话，可以限制四点坐标数值的最大最小值来规避这个现象

detect前向推理过程中，pred进行极大值抑制之后就出现负数了。。。
![图片](https://user-images.githubusercontent.com/49309820/121447435-37199e00-c9c8-11eb-817a-57d19b95e1ad.png)

**Comment by hongdesheng** [comment]
[    -21.108,     -81.009,      24.316,      226.04,     0.88116,           0]], dtype=float32)
bboxes_xyxy = pred_det[0][:, :4].astype('uint32')这个负数还很小的，变成32位直接出现了这么大的坐标
array([[       173, 4294967230,        611,        270]], dtype=uint32)
