### ISSUE TITLE
旋转检测框的角度

### ISSUE THREAD

**Issue by NephrenCake** [hukaixuan19970627/YOLOv5_DOTA_OBB#35]
## 角度一定需要在[0, 180)的范围吗？

如果要检测一个物体的具体方向，比如说不同旋转角度的字，那么角度能不能改成[0, 360)？

**Comment by hukaixuan19970627** [comment]
可以。找到detect类，把self.angles由180改为360就行了，但是这样通道数增加太多，再用csl的话就会大幅增加计算量；
你可以只在detect类中增加4个通道，专门用于预测旋转框四个点的顺序来确定物体的头部
