### ISSUE TITLE
Why some tensorboard data metrics not logged?

### ISSUE THREAD

**Issue by roberttorres67** [hukaixuan19970627/YOLOv5_DOTA_OBB#36]
## ❔Question
Why some tensorboard data metrics not logged?
![image](https://user-images.githubusercontent.com/50265550/122361312-fc55bf80-cf0b-11eb-901e-8f7ab55015b2.png)

**Comment by hukaixuan19970627** [comment]
results.txt:
[epoch/epochs-1 , mem , loss_obx , loss_obj ,  loss_cls  ,loss_angle ,
total_loss , targets_num , imgs.shape,  **precision , recall , mAP@.5 ,  
mAP@.5-.95, val_loss_box, val_loss_obj, val_loss_cls， val_loss_angle**]

I didn't add the code for the validation，so it is normal for the last eight data values to be zero

**Comment by roberttorres67** [comment]
> add the code for the validation

ok, when you add the code for the validation? :-)

**Comment by hukaixuan19970627** [comment]
Maybe never.
The rNMS is too inefficient to calculate，so it would cost a lot of time in training. 
You can use the evaluation.py to evaluate the detector.

**Comment by roberttorres67** [comment]
> Maybe never.
> The rNMS is too inefficient to calculate，so it would cost a lot of time in training.
> You can use the evaluation.py to evaluate the detector.

Thank you very much.
