### ISSUE TITLE
训这网络有什么技巧啊，感觉很难训，angle的loss很高（0.5几），很难降下去，训了10epoch精度还是0

### ISSUE THREAD

**Issue by 113HQ** [hukaixuan19970627/YOLOv5_DOTA_OBB#37]

**Comment by hukaixuan19970627** [comment]
请按照readme流程，detect可视化查看网络的学习情况，以及evaluation评估网络的性能。
至于为什么在线验证的所有精度均为0可以参考这个issue：
[#36 ](https://github.com/hukaixuan19970627/YOLOv5_DOTA_OBB/issues/36)
另外为了提高issue的效率，可以附上trainbatch0/1/2图片，loss曲线图，detect可视化结果图等相关数据以便于我快速定位问题

**Comment by 113HQ** [comment]
哦哦，明白了，那这样光看损失值很难判定什么时候训得差不多了。
哥，还有一个问题，训练的时候用不同长宽的图，标签位置会变。但是detect的时候我用了一张2413*5118的图，整图，检测出来并没有问题，这是为什么？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月19日(周六) 中午1:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 训这网络有什么技巧啊，感觉很难训，angle的loss很高（0.5几），很难降下去，训了10epoch精度还是0 (#37)




 
请按照readme流程，detect可视化查看网络的学习情况，以及evaluation评估网络的性能。
 至于为什么在线验证的所有精度均为0可以参考这个issue：
 #36 
 另外为了提高issue的效率，可以附上trainbatch0/1/2图片，loss曲线图，detect可视化结果图等相关数据以便于我快速定位问题

**Comment by hukaixuan19970627** [comment]
1. yolov5暂时不需要担心过拟合的问题，只要数据集不是小到离谱，Mosaic这种随机性极强的数据增广策略不会因为epoch太大而减少泛化性，所以你完全可以设置较大的epoch
2. readme里写了，训练的时候要注意HEIGHT=WEIGHT，因为目前这个标签数据格式方案暂时不是最优的，xywhθ中的wh和图像的宽高没有严格的定义关系，所以一旦图像宽高不相等，进行数据增强的时候归一化和反归一化就很容易计算错误，因此造成gtbox的偏移现象，其实只要把标签格式改为任意四点坐标格式，数据增强代码也对应修改就ok，不过这个问题可能等我忙完才会修复；

**Comment by zhenyuzhouiu** [comment]
>     1. yolov5暂时不需要担心过拟合的问题，只要数据集不是小到离谱，Mosaic这种随机性极强的数据增广策略不会因为epoch太大而减少泛化性，所以你完全可以设置较大的epoch
> 
>     2. readme里写了，训练的时候要注意HEIGHT=WEIGHT，因为目前这个标签数据格式方案暂时不是最优的，xywhθ中的wh和图像的宽高没有严格的定义关系，所以一旦图像宽高不相等，进行数据增强的时候归一化和反归一化就很容易计算错误，因此造成gtbox的偏移现象，其实只要把标签格式改为任意四点坐标格式，数据增强代码也对应修改就ok，不过这个问题可能等我忙完才会修复；

你好，不知道目前有没有修改好关于训练时， 图像宽高不相等，进行数据增强会出现错误的问题？谢谢！

**Comment by hukaixuan19970627** [comment]
> > ```
> > 1. yolov5暂时不需要担心过拟合的问题，只要数据集不是小到离谱，Mosaic这种随机性极强的数据增广策略不会因为epoch太大而减少泛化性，所以你完全可以设置较大的epoch
> > 
> > 2. readme里写了，训练的时候要注意HEIGHT=WEIGHT，因为目前这个标签数据格式方案暂时不是最优的，xywhθ中的wh和图像的宽高没有严格的定义关系，所以一旦图像宽高不相等，进行数据增强的时候归一化和反归一化就很容易计算错误，因此造成gtbox的偏移现象，其实只要把标签格式改为任意四点坐标格式，数据增强代码也对应修改就ok，不过这个问题可能等我忙完才会修复；
> > ```
> 
> 你好，不知道目前有没有修改好关于训练时， 图像宽高不相等，进行数据增强会出现错误的问题？谢谢！

已经完成了，但是没上传，数据都在内网里，预计九月底之前能上传
