### ISSUE TITLE
关于rbox_iou的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#38]
请问，我看到您在项目里写了计算四边形iou的函数，rbox_iou。但是您好像并没有用到这个函数。在训练过程中，找到与target相匹配的anchor的时候，仍然用的是bbox，而没有用rbox。这是为什么呢？
谢谢。

**Comment by hukaixuan19970627** [comment]
θ解耦出去单独作为一个分类任务了，使用BCE作为损失函数，剩余四个参数作为另一个回归任务，因此使用水平框的CIoU作为回归loss。
置信度损失有两种选择，正样本全部置为1或者以IoU作为该置信度损失分支的权重，采用后者预测出来的置信度会降低但是整体精度会提升，这里采用的是后者。所以这里置信度损失的权重又有两种选择，一个是水平IoU，另一个是RIoU，后者明显更好，但是我写的RIoU的计算效率太低，虽然最后的精度会上升一点点但是运算时间增加了一倍，性价比不高，因此没有启用

**Comment by kuazhangxiaoai** [comment]
我看算法默认的输入为1024*1024，这个尺寸是不是很大呢？需要什么设备才能训练起来呢？
谢谢

**Comment by hukaixuan19970627** [comment]
> 我看算法默认的输入为1024*1024，这个尺寸是不是很大呢？需要什么设备才能训练起来呢？
> 谢谢

我应用在遥感检测领域所以尺寸比较大，你完全可以根据你自己的情况设置成你的数据集大小，具体什么设备得看你使用什么规模的模型以及batchsize的大小

**Comment by Helloworld777777** [comment]
> θ解耦出去单独作为一个分类任务了，使用BCE作为损失函数，剩余四个参数作为另一个回归任务，因此使用水平框的CIoU作为回归loss。 置信度损失有两种选择，正样本全部置为1或者以IoU作为该置信度损失分支的权重，采用后者预测出来的置信度会降低但是整体精度会提升，这里采用的是后者。所以这里置信度损失的权重又有两种选择，一个是水平IoU，另一个是RIoU，后者明显更好，但是我写的RIoU的计算效率太低，虽然最后的精度会上升一点点但是运算时间增加了一倍，性价比不高，因此没有启用

maybe is your RIoU don't care all.  ep: The Intersections and the endpoints coexist.
