### ISSUE TITLE
自定义数据训练问题

### ISSUE THREAD

**Issue by 113HQ** [hukaixuan19970627/YOLOv5_DOTA_OBB#39]
## ❔Question
大佬，我用这个网络训练八类飞机目标的时候没问题，损失下降的很正常，检测效果也还可以
![image](https://user-images.githubusercontent.com/57024487/123529884-5bdf7680-d727-11eb-8633-f779a4afe872.png)
但是我把它归为一类之后，其他参数也没变，box损失根本降不下去，定位效果很差，这是为什么
![image](https://user-images.githubusercontent.com/57024487/123529902-803b5300-d727-11eb-9b51-2203290a0b92.png)

**Comment by hukaixuan19970627** [comment]
https://zhuanlan.zhihu.com/p/358072483
具体原因可以看一下这篇文章最后的常见问题总结。

**省流助手：把nc改为2即可**

**Comment by 113HQ** [comment]
啊？我傻了！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月27日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 自定义数据训练问题 (#39)




 
https://zhuanlan.zhihu.com/p/358072483
 具体原因可以看一下这篇文章最后的常见问题总结。
 
省流助手：把nc改为2即可

**Comment by 113HQ** [comment]
nc改成2之后损失是降了些 ，能检测出一些飞机，但是效果远不如我分8类来的好呀！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月27日(周日) 下午5:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 自定义数据训练问题 (#39)




 
https://zhuanlan.zhihu.com/p/358072483
 具体原因可以看一下这篇文章最后的常见问题总结。
 
省流助手：把nc改为2即可

**Comment by hukaixuan19970627** [comment]
方便发下两种处理方法（nc=8和2）的trainbatch0/1/2，loss曲线图，检测的可视化图给我看看吗？这样找问题更快一点

**Comment by 113HQ** [comment]
> 方便发下两种处理方法（nc=8和2）的trainbatch0/1/2，loss曲线图，检测的可视化图给我看看吗？这样找问题更快一点

nc=8的训练曲线就是提问时候的第一张图，box损失可以降到0.06以下，nc=2的时候训练150epoch，主要就是box损失只从0.16下降到0.08几，其他损失都正常。检测图如下，分别是nc=8和nc=2(其他图有很多检不出来的，还有离谱的长框)：
nc=8:
![image](https://user-images.githubusercontent.com/57024487/123639906-36e82200-d853-11eb-949b-08b8d1b54548.png)
nc=2:
![image](https://user-images.githubusercontent.com/57024487/123639593-ef619600-d852-11eb-932b-c6d427de0982.png)

**Comment by hukaixuan19970627** [comment]
你觉得有问题的那个loss曲线图没发哟，那我就只能猜，假设nc为2和8的loss收敛曲线几乎相同（就是box loss值不同）：
1. 看loss曲线的话还未完全收敛，开了mosaic整体网络的收敛时间会延长，不过泛化性也会随之提升，可以尝试epoch增大，另外某些应用场景mosaic触发概率设为0.5精度表现会更好；
2. 有没有调过参数呢，0.05的置信度阈值本来就是为了刷点而设置的，即为了保证召回率会适当增加错检率，实际应用的时候置信度阈值是会设的比较高的。

**Comment by 113HQ** [comment]
> 你觉得有问题的那个loss曲线图没发哟，那我就只能猜，假设nc为2和8的loss收敛曲线几乎相同（就是box loss值不同）：
> 
> 1. 看loss曲线的话还未完全收敛，开了mosaic整体网络的收敛时间会延长，不过泛化性也会随之提升，可以尝试epoch增大，另外某些应用场景mosaic触发概率设为0.5精度表现会更好；
> 2. 有没有调过参数呢，0.05的置信度阈值本来就是为了刷点而设置的，即为了保证召回率会适当增加错检率，实际应用的时候置信度阈值是会设的比较高的。

明后天给你发个图，那个超参数文件只改了angle,1.0变0.5，但两次训练用的超参数是一样的，我觉得训150次已经很多了，也就4000多张800*800的训练图，预训练权重是你的DOTA，上图detect的时候我设置的置信度阈值是0.3，整体来说nc=2的漏检和误检多很多，框的定位也差一些。主要是我觉得就检测一类，它应该更简单，更好训

**Comment by 113HQ** [comment]
> 你觉得有问题的那个loss曲线图没发哟，那我就只能猜，假设nc为2和8的loss收敛曲线几乎相同（就是box loss值不同）：
> 
> 1. 看loss曲线的话还未完全收敛，开了mosaic整体网络的收敛时间会延长，不过泛化性也会随之提升，可以尝试epoch增大，另外某些应用场景mosaic触发概率设为0.5精度表现会更好；
> 2. 有没有调过参数呢，0.05的置信度阈值本来就是为了刷点而设置的，即为了保证召回率会适当增加错检率，实际应用的时候置信度阈值是会设的比较高的。

nc=2的损失曲线图：
![results](https://user-images.githubusercontent.com/57024487/123923970-17b8d400-d9bc-11eb-9d7e-67c538f9265d.png)

train_batch:
![train_batch1](https://user-images.githubusercontent.com/57024487/123924004-1e474b80-d9bc-11eb-9e9a-745246b8c7d7.jpg)

**Comment by hukaixuan19970627** [comment]
emmm, 挺符合实际的，分类loss因为没有第二类标签，网络完全可以不进行分类通道分支的参数更新，因此分类loss一直在0附近。
相比nc=8的loss曲线，nc=2的box和置信度loss曲线完全没收敛，并且θloss提前收敛了，从可视化的表现上就是预测框的角度正确，但是框的位置以及其置信度不怎么准确，三者要尽量保持收敛同步网络才会有比较好的效果；
你可以尝试下调节各个loss的权重，分类loss与θloss权重调低，box和置信度loss的权重调高，hyp.×××.yaml文件里可以调节。

**Comment by 113HQ** [comment]
好的，我试试，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月30日(周三) 晚上11:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 自定义数据训练问题 (#39)




 
emmm, 挺符合实际的，分类loss因为没有第二类标签，网络完全可以不进行分类通道分支的参数更新，因此分类loss一直在0附近。
 相比nc=8的loss曲线，nc=2的box和置信度loss曲线完全没收敛，并且θloss提前收敛了，从可视化的表现上就是预测框的角度正确，但是框的位置以及其置信度不怎么准确，三者要尽量保持收敛同步网络才会有比较好的效果；
 你可以尝试下调节各个loss的权重，分类loss与θloss权重调低，box和置信度loss的权重调高，hyp.×××.yaml文件里可以调节。

**Comment by hukaixuan19970627** [comment]
效果有改善吗

**Comment by 113HQ** [comment]
有，正常了，训了200次，但好像有点过拟合了。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月2日(周五) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 自定义数据训练问题 (#39)




 
效果有改善吗

**Comment by 113HQ** [comment]
今晚看了一下验证数据，粗略做了下统计，发现nc=8的时候分类是差了一些，但是飞机召回率高，分一类之后，在战斗机这类机型上的召回率反而不如分8类了。。。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月2日(周五) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hukaixuan19970627/YOLOv5_DOTA_OBB] 自定义数据训练问题 (#39)




 
效果有改善吗
