### ISSUE TITLE
你的模型不支持pytorch1.8，目前只能1.6

### ISSUE THREAD

**Issue by gengyanlei** [hukaixuan19970627/YOLOv5_DOTA_OBB#4]
应该不是bug，不过你的opencv版本建议注明 小于4.5.1吧

**Comment by gengyanlei** [comment]
应该不是bug

**Comment by gengyanlei** [comment]
不错效果，这是用无人机拍的，看来DOTA的场景也适合无人机影像，比其它基于DOTA的项目效果好多了。我前面都是基于UCAS_AOD数据集测试的

**Comment by hukaixuan19970627** [comment]
对的。opencv版本必须小于4.5，4.5以上版本的cv2.minAeraRect()生成的最小外接矩形框θ的所属范围已经变了，所以不适用当前项目的代码。目前我已经将requirements.txt更新

**Comment by Allenstin** [comment]
给作者大大的赞，写的很详细，这份代码pytorch1.6, cv<4.5就能跑了。谢谢作者
