### ISSUE TITLE
关于重新计算anchor的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#40]
请问，大佬，您在重新计算anchor的时候，说是利用了遗传算法+kmeans。但是，我并没有看到遗传 算法，倒是看到了kmeans了。
![image](https://user-images.githubusercontent.com/54108453/123548566-d942cf80-d797-11eb-84e4-cce19299f2d1.png)

**Comment by hukaixuan19970627** [comment]
计算anchor就是kmeans，整套流程都没有用到遗传算法，你是从注释里面看到的遗传算法吗？
这个项目的代码里面有很多注释，有很多是我初学的时候不懂然后加上的，有一些注释是有问题的，而且注释太多也不美观，但是把注释删掉又太费精力所以我就没改
