### ISSUE TITLE
swig执行报错

### ISSUE THREAD

**Issue by tuoxiexiansheng** [hukaixuan19970627/YOLOv5_DOTA_OBB#42]
## ❔Question
![image](https://user-images.githubusercontent.com/22231410/123757010-1cb05180-d8f0-11eb-9c04-85300591f851.png)
大佬好，请问我在执行
python setup.py build_ext --inplace 这条命令的时候会报这样的错误请问是什么原因呢？操作系统是windows10

**Comment by hukaixuan19970627** [comment]
linux系统按照readme流程来安装环境的话不会出现问题；
windows基本上编译swig这一步就会失败，不过也有人成功过，你搜索一下swig windows DOTA_devkit关键词，有人在博客上总结过经验

**Comment by tuoxiexiansheng** [comment]
> linux系统按照readme流程来安装环境的话不会出现问题；
> windows基本上编译swig这一步就会失败，不过也有人成功过，你搜索一下swig windows DOTA_devkit关键词，有人在博客上总结过经验

好的，谢谢大佬

**Comment by weiyidawang** [comment]
把polyiou.cpp用Notepad打开，编码->使用UTF-8-BOM编码->保存即可。
![bfdb015cc592386d8b639fecc33bb52](https://user-images.githubusercontent.com/95668069/165532369-5e2ef111-e8eb-470e-a6a1-6a8468747a8d.png)
