### ISSUE TITLE
python detect.py 报错

### ISSUE THREAD

**Issue by tuoxiexiansheng** [hukaixuan19970627/YOLOv5_DOTA_OBB#43]
## ❔Question
![image](https://user-images.githubusercontent.com/22231410/123800982-6a42b380-d91c-11eb-8406-251aea7a43ee.png)
带佬又是我，我由于手边没安装linux电脑，所以暂时想用windows跑一下demo，调用命令 python detect.py 报出了如上图错误，我不太清楚如何解决这个error。

**Comment by hukaixuan19970627** [comment]
环境没装好，安装环境过程只要有报错，运行就不会成功，你这明显shapely安装有问题
