### ISSUE TITLE
断点继续训练问题

### ISSUE THREAD

**Issue by dagongren11** [hukaixuan19970627/YOLOv5_DOTA_OBB#44]
## Additional context
![image](https://user-images.githubusercontent.com/86774750/124102980-6d13e480-da93-11eb-9b7d-241fd3b6ba7a.png)

![image](https://user-images.githubusercontent.com/86774750/124103048-7c932d80-da93-11eb-8990-262dc4e9ef35.png)

**Comment by hukaixuan19970627** [comment]
--weights “runs/exp0/weights/???.pt”，就可以自动重续断点

**Comment by dagongren11** [comment]
> --weights “runs/exp0/weights/???.pt”，就可以自动重续断点

好的好的，谢谢大佬(*￣∇￣*)
