### ISSUE TITLE
反归一化的问题

### ISSUE THREAD

**Issue by sangsasi** [hukaixuan19970627/YOLOv5_DOTA_OBB#45]
## ❔Question
博主您好。我用您的模型训练自己的数据集效果很好，中心点的坐标和角度都比较准确，但是检测时画的框有些是正常的，有些极其瘦长，框里的图形已经看不出是标签对应的图形了，我看了下detect中pred的数据，好像model输出的label直接为反归一后的label。我看您的注解里有些label是（:w,h,:）有些是(:longside,shortside,:)，反归一时会用w*img_w,h*img_h，w,h并不平行于图像的边，可能是这里造成我的结果有瘦长的框出现，但是有些框又是正常的，我看了好几天代码，实在是想不通，希望能够得到您的解答，谢谢。

**Comment by hukaixuan19970627** [comment]
可以把注释删掉，我是基于原始yolov5改的，有些注释是我刚开始看yolov5代码时加上的，但是修改为旋转检测之后有些注释就没用了，不过注释太多我也没来得及全部改成旋转检测的注释，detect部分是没啥问题的，我拿宽高不一致的DOTA图像检测可视化一切都很正常；
既然有的框正常拟合，有的框拟合的不够好，那说明是网络还没完全收敛的问题，你看loss变化曲线是可以看出来的；
trainbatch012图片可以直接查看数据增强后的结果，通过它可以判断是否标签制作有问题，训练结束生产的results图片或tensorboard可以可视化网络的收敛情况，loss还在降说明还得继续训练，有的loss下降的快有的loss下降的慢，说明是你的数据集不适合当前的loss权重，可以自行修改，尽量确保各个分支的loss下降趋势一致最终才会有比较好的检测效果。

**Comment by sangsasi** [comment]
感谢，我把图片改为正方形之后就没问题了。

**Comment by lanjunb** [comment]
您好，请问把图片改成正方形后是不是要重新标注啊，之前的标签文件就不能用了吧

**Comment by sangsasi** [comment]
> 您好，请问把图片改成正方形后是不是要重新标注啊，之前的标签文件就不能用了吧

是的

**Comment by hukaixuan19970627** [comment]
> 您好，请问把图片改成正方形后是不是要重新标注啊，之前的标签文件就不能用了吧

如果直接resize的话会导致图像变形，此时需要重新修改labels，但如果是使用pad让图像宽高一致的话，labels不需要更改

**Comment by phunix9** [comment]
> 感谢，我把图片改为正方形之后就没问题了。

你好，你说的瘦长的框是指类似平行四边形吗？我在跑了10个epoch后，检测结果有的是正常的矩形框，有的是平行四边形框，不知道是不是训练不够？我的训练数据都是正方形的

**Comment by sangsasi** [comment]
> > 感谢，我把图片改为正方形之后就没问题了。
> 
> 你好，你说的瘦长的框是指类似平行四边形吗？我在跑了10个epoch后，检测结果有的是正常的矩形框，有的是平行四边形框，不知道是不是训练不够？我的训练数据都是正方形的

我只在可视化的时候出现过平行四边形，是原图片的长宽比不一样导致的。你说的检测结果是detect.py的结果吗？不知道你有没有改过文件内容。建议你debug一下detect.py，检查pred到rbox的过程，cv2.boxPoints得到的结果是矩形的四个点的坐标，看看这个过程有没有出现问题。你也可以看看出现正常矩形和平行四边形框的图片之间有没有共同的区别，比如平行四边形的框角度和长宽比。

**Comment by phunix9** [comment]
> > > 感谢，我把图片改为正方形之后就没问题了。
> > 
> > 
> > 你好，你说的瘦长的框是指类似平行四边形吗？我在跑了10个epoch后，检测结果有的是正常的矩形框，有的是平行四边形框，不知道是不是训练不够？我的训练数据都是正方形的
> 
> 我只在可视化的时候出现过平行四边形，是原图片的长宽比不一样导致的。你说的检测结果是detect.py的结果吗？不知道你有没有改过文件内容。建议你debug一下detect.py，检查pred到rbox的过程，cv2.boxPoints得到的结果是矩形的四个点的坐标，看看这个过程有没有出现问题。你也可以看看出现正常矩形和平行四边形框的图片之间有没有共同的区别，比如平行四边形的框角度和长宽比。

谢谢指导，我跑了100个epoch后，使用detect.py检测一张图片。有的检测框是正常带角度的矩形，有的检测框是带角度的平行四边形，我再看看坐标转换的过程。

**Comment by hukaixuan19970627** [comment]
出现平行四边形的话可以参考一下这篇的解决方法：
https://zhuanlan.zhihu.com/p/385701722
