### ISSUE TITLE
训练时的train_batch图片上检测框位置偏移

### ISSUE THREAD

**Issue by surefyyq** [hukaixuan19970627/YOLOv5_DOTA_OBB#46]
## ❔Question
   @hukaixuan19970627 略哥你好，我使用的是全新的自制数据集，根据YOLO_Transform.py将DOTA格式的标注转为YOLO格式后可视化如下：

![image](https://user-images.githubusercontent.com/26786673/124424235-4a3a4680-dd99-11eb-8353-f2dea6370f53.png)

但是开始训练后，从train_batch012图上发现送入模型的图片上一些角度的检测框发生了偏移，最终训练结果也是如此：

![image](https://user-images.githubusercontent.com/26786673/124424424-94232c80-dd99-11eb-8a30-70b4c9a44e93.png)

请问这可能会和哪里有关系，如何修改呢？感谢！

**Comment by surefyyq** [comment]
找到原因了，是因为我输入的图片长宽不相等，严格根据知乎上的数据处理流程进行裁切就可以解决了

**Comment by hukaixuan19970627** [comment]
emmm，你让图像的宽高相等就可以了；
比如你的数据集最大的图像为640*620，那么数据集统一先pad成640*640，再进行label转换以及后续的输入yolov5网络操作；
嫌麻烦的话可以用DOTA_devkit_YOLO中的split.py函数完成这一操作，subsize设为640即可（**subsize > max_image_height**）
