### ISSUE TITLE
关于图像分割检测小目标的问题以及提高分类

### ISSUE THREAD

**Issue by YocurryC** [hukaixuan19970627/YOLOv5_DOTA_OBB#47]
## ❔Question
请教大佬，自己利用该repo在FAIR1M数据集上进行训练，原图像大小多为1000×1000或者1500×1500像素，当自己不对原图像进行分割直接crop_size=1024进行训练，最终评价结果得到船、飞机等较小物体的类别评价指标明显不好，但篮球场、网球场等大物体评价指标较高，在知乎上问了略略略大佬，不知道自己如下理解对不对：就是对于yolo下采样为8倍的分支，假设原图大小为800×800，那么下采样得到的feature map为100×100，分割之后原图大小假设为400×400，那么8倍下采样得到的feature map为50×50，但是对于物体来说下采样之后尺度是不变的，就是不管图像尺寸是多大，8倍下采样之后物体对应的特征尺度是不变的，那么分割提高小目标检测的准确率的原理是什么呢？谢谢！
还有就是怎么提高物体的分类精度呢？有些物体是被框出来了但是分类错误了，谢谢！

**Comment by hukaixuan19970627** [comment]
1.关于为什么要切割：
![image](https://user-images.githubusercontent.com/72599120/125164038-b9ad9d00-e1c2-11eb-909b-96402df04f42.png)
2. 私聊的时候我回答过了，sigmoid本身有类别不互斥的特性，即一个物体可能会有多个类别的预测结果，尤其是类间差异小的物体特别容易发生这种情况，比如large vehicle与small vehicle两个类别经常同时出现在同一个vehicle物体上，代码默认设置是会显示多标签label的，你说的“分类错误”的物体不应该只出现一种类别的框才对，如果只出现了一种类别的框并且这个类别预测是错的，说明错误的类别score是所有类别中最高的，并且其他类别的score低于置信度阈值因此没有显示，调低置信度阈值是可以看到正确类别的预测的（如果看不到，说明class分支还没收敛），如果想实现类别互斥（即不支持多标签label），可以把sigmoid换成softmax

**Comment by YocurryC** [comment]
也就是说将图像分割主要原因还是因为显存的问题，理论上不能提高检测小物体的能力？

**Comment by YocurryC** [comment]
也就是说将图像进行分割主要还是因为显存的问题，理论上不能提高检测小物体的能力？嗯对分类错误应该是取了score最高的那个类别所对应的标签不对，另外还想请教一下 错检的话（也就是score小于置信度阈值的）导致FP增大，漏检的话导致FN增大，应该都会导致mAP评价指标的下降吧？

**Comment by hukaixuan19970627** [comment]
1.理论上大图片不分割会降低检测小物体的能力
2. 不一定，这些指标都是受多个纬度的影响的，一般TP提高了，FP也会相应增加，最后mAP指标是否下降得看多个指标的共同影响

**Comment by YocurryC** [comment]
感谢解答。
