### ISSUE TITLE
重叠物体检测问题

### ISSUE THREAD

**Issue by 2387649299** [hukaixuan19970627/YOLOv5_DOTA_OBB#48]
修改处：将我的图片替换到 DOTA_demo_view/images/文件夹下，对应txt标签文件放到 DOTA_demo_view/labels/文件夹下。train.py中--weights使用yolov5m.pt，--cfg使用yolov5m.yaml（nc改成了2），--data使用DOTA_ROTATED.yaml（nc改成2，names改成[’up’,’down’]）。

![results](https://user-images.githubusercontent.com/49848733/125182913-b3f89b80-e244-11eb-8605-c007ee364de0.png)
![20200929223700486](https://user-images.githubusercontent.com/49848733/125182992-4b5dee80-e245-11eb-96e5-7c729c42af62.png)

**Comment by hukaixuan19970627** [comment]
trainbatch0/1/2提交一下

**Comment by 2387649299** [comment]
![1](https://user-images.githubusercontent.com/49848733/125183911-94fe0780-e24c-11eb-85ce-b4ceb7c16355.jpg)
这个吗？

**Comment by 2387649299** [comment]
![1](https://user-images.githubusercontent.com/49848733/125183922-a34c2380-e24c-11eb-921b-5cbc86d8507a.jpg)

**Comment by 2387649299** [comment]
603张图片的数据集，--batch-size设置为16

**Comment by hukaixuan19970627** [comment]
是训练生成的trainbatch0.jpg trainbatch1.jpg trainbatch2.jpg

**Comment by 2387649299** [comment]
![train_batch1](https://user-images.githubusercontent.com/49848733/125187456-5a06ce80-e262-11eb-9ee8-71c2112546b1.jpg)
![train_batch2](https://user-images.githubusercontent.com/49848733/125187459-5bd09200-e262-11eb-8ea5-ac6ac6efac82.jpg)
![train_batch0](https://user-images.githubusercontent.com/49848733/125187460-5c692880-e262-11eb-8cc1-9583a7d94bb5.jpg)

**Comment by 2387649299** [comment]
好像是我resize了我的数据集从1280x960，变成1024x1024导致trainbatch0.jpg trainbatch1.jpg trainbatch2.jpg错乱了，我用原来的1280x960试后trainbatch0.jpg trainbatch1.jpg trainbatch2.jpg正常了，等会再看看结果

**Comment by hukaixuan19970627** [comment]
pad成长宽一致，而不是resize，强行resize会导致图像失真。

**Comment by shenhaibb** [comment]
你最后精度多少啊 我自己做的数据集 精度才35 。。。。。。。。。。
