### ISSUE TITLE
关于RoI transformer的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#49]
请问，您做遥感物体检测的时候，研究过RoI Transoformer算法吗？

**Comment by hukaixuan19970627** [comment]
了解过，不过我是因为实际项目需要用到旋转检测，因此对检测的实时性有一定要求，所以不考虑one stage以外的检测算法。ROI transformer已经属于三阶段检测器了
