### ISSUE TITLE
关于输出的result中的mAP计算

### ISSUE THREAD

**Issue by Uncolor-Duck** [hukaixuan19970627/YOLOv5_DOTA_OBB#50]
## ❔我得到的输出result.txt后八位始终是零
我在train.py中只能找到result的初始化（归零）操作，但无法找到对它赋值的操作，是否是缺少了修改的模块，如果想要添加需要在哪里加。希望得到回复。感谢

**Comment by 2387649299** [comment]
作者博客有解释，没时间写这块了

**Comment by hukaixuan19970627** [comment]
#36

**Comment by Uncolor-Duck** [comment]
好的，感谢，我试试evaluate.py
