### ISSUE TITLE
关于LetterBox的问题？

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#51]
请问，关于Yolov5 在预测阶段中，不同通的尺寸的图片是如何处理的？好像用了个LetterBox函数，但是，经过LetterBox处理的图片仍然不是1024*1024。但这样不会影响到预测效果吗？

**Comment by hukaixuan19970627** [comment]
detect.py支持任意尺寸的图像预测
