### ISSUE TITLE
DOTAv1.5验证集检测及mAP的问题

### ISSUE THREAD

**Issue by fzhq** [hukaixuan19970627/YOLOv5_DOTA_OBB#53]
## ❔Question
大佬，您好。我使用了您的这份代码，在其中加了一个检测层进行训练，按理说应该会对小目标更加敏感吧，但在进行评估的时候，mAP异常的低，请问怎么回事呢？
![image](https://user-images.githubusercontent.com/70955329/126021763-856711f9-20e9-43b8-8171-5c13c143f66c.png)
图片大小我是切割成512x512了，评估的时候按照您写的先检测后合并进行的，训练Epoch=50，下面是一些相关结果信息：
train_batch012.jpg：
![train_batch0](https://user-images.githubusercontent.com/70955329/126021703-4a61209a-85ad-4137-a8d8-308ad73191c6.jpg)
![train_batch1](https://user-images.githubusercontent.com/70955329/126021709-9e5fcd49-1d7f-4e61-a44e-da35706b8bff.jpg)
![train_batch2](https://user-images.githubusercontent.com/70955329/126021710-4bab0883-460a-43f2-a31a-f86425d12bfa.jpg)
detect的效果图：
![P0305_](https://user-images.githubusercontent.com/70955329/126021720-a2cf45bb-6596-4856-a26a-96125ab9da95.png)
![P0696_](https://user-images.githubusercontent.com/70955329/126021722-ef6e8871-b56b-4e19-8a1f-bf269047e740.png)
![P1128_](https://user-images.githubusercontent.com/70955329/126021727-3d431c78-8c4d-41d1-8df5-82a0be025514.png)
loss曲线图;
![results](https://user-images.githubusercontent.com/70955329/126021737-859510ec-061d-4d20-9200-d0148bacf2e1.png)

**Comment by hukaixuan19970627** [comment]
你加的P6（下采样倍数为2的6次方）检测层还是P2(下采样倍数为2的2次方)检测层？

**Comment by fzhq** [comment]
> 你加的P6（下采样倍数为2的6次方）检测层还是P2(下采样倍数为2的2次方)检测层？
P2，增加了一个大的特征图

**Comment by hukaixuan19970627** [comment]
原始项目改动了哪些地方发一下，光添加detect层是不行的，yolov5 PAFPN会对P3 P4 P5进行融合操作，这一部分也要改，不然原始P2不参与浅层深层特征层的融合会导致其语义信息不够抽象，大致表现就是类别预测这一块准确率不高但是定位效果应该还可以（尤其是当你使用yolov5s/m这一类小参数模型时影响会特别明显）；

另外计算loss时每个检测层的权重设置是不同的，你可以到compute loss中修改这一部分，如果不修改的话，按照你目前的设置，其权重默认为[4, 1, 0.4, 0.1]，这样的话P5的作用就太低了，那么一些大感受野的物体学习效果就会比较差，DOTA数据集中的物体尺度变化比较剧烈，所以这一部分最好还是多做实验调整一下比较好

**Comment by fzhq** [comment]
> 原始项目改动了哪些地方发一下，光添加detect层是不行的，yolov5 PAFPN会对P3 P4 P5进行融合操作，这一部分也要改，不然原始P2不参与浅层深层特征层的融合会导致其语义信息不够抽象，大致表现就是类别预测这一块准确率不高但是定位效果应该还可以（尤其是当你使用yolov5s/m这一类小参数模型时影响会特别明显）；
> 
> 另外计算loss时每个检测层的权重设置是不同的，你可以到compute loss中修改这一部分，如果不修改的话，按照你目前的设置，其权重默认为[4, 1, 0.4, 0.1]，这样的话P5的作用就太低了，那么一些大感受野的物体学习效果就会比较差，DOTA数据集中的物体尺度变化比较剧烈，所以这一部分最好还是多做实验调整一下比较好
好的，谢谢大佬。我只改动了图下的部分：
![image](https://user-images.githubusercontent.com/70955329/126098080-ccca9d69-84fb-4a29-90e5-b883ea0f1194.png)

**Comment by hukaixuan19970627** [comment]
结构看起来没啥问题，建议再检查一下loss各个尺度特征层的权重，从你这边可视化的角度来看稍微大一点的物体就检测不到了，权重的设置是一方面，还有anchor的代码这一块建议你也看一下，我现在无法查看代码，可能原始yolov5无法根据当前尺度的特征图生成对应的anchor（添加P6是可以的，反向添加P2会不会影响不同尺度anchor的分配这个得看具体代码）

**Comment by fzhq** [comment]
嗯嗯好的
