### ISSUE TITLE
关于NMS和预测角度的问题

### ISSUE THREAD

**Issue by YocurryC** [hukaixuan19970627/YOLOv5_DOTA_OBB#54]
##大佬再打扰一下，
1.repo里面在detect.py的时候会有一个NMS，这个NMS的过程如下图所示，所以这个NMS做完会出现一个物体被多个不同类别的框框住的现象；然后evalution.py中merge的时候也会有一个NMS，但是这个NMS对于每个物体只会保留一个置信度最大的框（不管是什么类别），这个理解对么？然后计算AP的时候就没有置信度阈值了？
![image](https://user-images.githubusercontent.com/60910771/126076115-c92d1034-ed75-42d8-9abf-18ff6518fe93.png)
2.进行detect并且merge之后检测的物体角度会存在问题，下面第一张图检测得到的，第二张图是原来标记图，这个问题是什么原因呢？该怎么解决呢？
![image](https://user-images.githubusercontent.com/60910771/126076149-607eef26-b502-4a27-a753-ba302cc7eaa0.png)
![image](https://user-images.githubusercontent.com/60910771/126076151-e98f6f51-6233-49f0-a17a-fd9cecaeda20.png)
3.对于小目标的话，如果网络训练是1024×1024的尺度，但是在detect的时候图片像素可以小于训练的时候的像素尺度，比如裁剪为512甚至256来检测是不是应该对小目标更友好一点？但是在做NMS时把置信度阈值设为0.05已经保证检出的物体超过原来标记的物体了。
谢谢大佬！

**Comment by hukaixuan19970627** [comment]
1. repo中的nms与普通的nms原理上没有不同，唯一区别在于IoU计算方式为任意四边形的IoU, 另外repo支持多类别预测，所以nms时只会在同类别的bbox之间进行。Results Merge函数的nms同上，因为切割的图像是有重叠区域的，合并的时候自然还要进行一次nms
2. 可以把原始项目改动的地方，trianbatch012，loss曲线，detect可视化图片（merge前与merge后），把一切能描述清楚问题的信息一起放上来，这样效率高一点。你这明显是角度还没收敛，跟merge没关系
3. resize等各种会引起图像信息损失的操作才会影响小目标的检测效果，如果想提高小目标的检测效果，大尺度测试是提点很明显的tricks

**Comment by YocurryC** [comment]
1.repo里面在merge的时候应该是把所有框不分类别了，如下图，第一张是before merge，第二张是after merge，而该物体label应该是Boeing737，这就会导致分类错误出现错检，这种情况是训练的问题么还是推理过程中参数的设置呢？这种小物体是不是本来就难识别呢？
before merge
![before](https://user-images.githubusercontent.com/60910771/126253082-225fe81a-bf99-4ba6-96a7-c7fac47ed9c9.png)

after merge
![after](https://user-images.githubusercontent.com/60910771/126253087-4e729166-a5e9-43dd-b61c-006f744eb789.png)

merge时候采用的NMS code
![code](https://user-images.githubusercontent.com/60910771/126253089-ec370fb2-d91e-46d4-81ee-bc4750f4ff9a.png)

2.为什么大尺度是提点的tricks呢？大尺度和小尺度对于一个物体所能利用的像素数不变呢？谢谢大佬

**Comment by YocurryC** [comment]
也就是说检测结果中正确分类的物体的类别置信度小于错误分类的类别置信度，那这个应该是训练的cls loss的问题么？是在自己数据集上基于yolov5m.pt训练了500个epochs，训练的时候的图像大小是512×512，但是detect的时候设置的大小是3000，原图大小为1000×1000或1500×1500或3000×3000（是我detect的大小不合适？）
![image](https://user-images.githubusercontent.com/60910771/126257686-17a55a96-0afa-42c9-9bdb-da6fa642a08a.png)
谢谢大佬！

**Comment by hukaixuan19970627** [comment]
1. detect后保存的结果是支持多类别预测的，但是用evaluation.py中进行result merge的时候没有添加这部分功能，你如果想从始至终都实现多类别预测的话可以做如下更改：（1）修改detect.py生成的txt格式，直接将检测结果分类并存入Task1_classname.txt中  (2) 再调用DOTA_devkit中的Result_merge.py即可合并分割图像的检测结果  (3)直接调用DOTA_devkit中的dota_evaluation_task1.py输出评估结果；
2. sigmoid在类间差距比较小的数据集中分类效果相比softmax会差一点，如果你对分类精度要求特别明确的话，将类别通道数据的sigmoid函数替换为softmax，softmax具有类别互斥的特性，在类别细分的场景应用中比较常用；
3. 对于小目标较多的数据集而言，在图像输入网络结构之前的任何会引起图像信息丢失的操作都是会掉点的，所以相对来说大尺度就是提点的trick了，另外基本上所有的网络结构都是提取中大物体的能力比较强，如果能通过增大尺度使得小目标变为中等大小的目标，也是能提高小目标的检测精度的，不过整体精度能否提高就是另一回事了；
4. detect的size尽量与训练时保持一致

**Comment by ypd-wblx** [comment]
能否在代码中增添一个步骤，比较所有目标边界框的IOU，如果两个不同类别目标的边界框之间的IOU较大，去掉其中置信度较小的一个检测结果，这样是不是能解决一个目标被检测出两个类别？
