### ISSUE TITLE
关于您代码的纯python版本（Another version of YOLOv5_DOTA_OBB without c++ extension）

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#55]
我仿照您的代码，改了个纯python版本的，主要改了poly_iou.py文件，https://github.com/kuazhangxiaoai/Yolov5_OBB_Detection。

**Comment by hukaixuan19970627** [comment]
厉害。
这个计算效率有提升吗，尤其是nms那一块

**Comment by kuazhangxiaoai** [comment]
> 厉害。
> 这个计算效率有提升吗，尤其是nms那一块

因为我没有LINUX的系统，所以，不知道您之前的效率如何，我这边还可以，知行一次iou大概0.008s。
![image](https://user-images.githubusercontent.com/54108453/126579340-67fceeae-a1fc-4630-b14b-70494d53372c.png)

**Comment by babyta** [comment]
测试了两版代码 python实现的nms效率很低，平均会慢5倍以上
