### ISSUE TITLE
测试问题

### ISSUE THREAD

**Issue by xiaofeng-c** [hukaixuan19970627/YOLOv5_DOTA_OBB#56]
## ❔Question
你好,测试时出现下面这个问题,查了一下还没有解决,请问是opencv版本不对吗?

## Additional context
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'boxPoints'
> Overload resolution failed:
>  - Can't parse ''box' center point'. Sequence item with index 0 has a wrong type
>  - Can't parse ''box' center point'. Sequence item with index 0 has a wrong type

**Comment by fxcdl** [comment]
opencv版本使用4.1.2就行了

**Comment by xiaofeng-c** [comment]
好的,谢谢!
