### ISSUE TITLE
(About mAP@0.5 on DOTAv1.5-testdev)关于mAP无法达到预期效果的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#58]
![image](https://user-images.githubusercontent.com/54108453/127081347-cbd76141-2e8d-47cc-92ce-209a3d062467.png)
mAP值总是在62左右徘徊，和67差了不少。detect方法采用分割的方法，取消了dataset的letterbox函数。具体代码：在
https://github.com/kuazhangxiaoai/Yolov5_OBB_Detection/blob/master/detect.py
以及
https://github.com/kuazhangxiaoai/Yolov5_OBB_Detection/blob/master/utils/datasets.py
请您帮我看一下，十分感谢胡大神。

**Comment by hukaixuan19970627** [comment]
small－vehicle这个类的AP有点过于低了，建议找几张车多的图可视化看一下，精度不足的原因可能是啥，是角度学的不准还是召回率就不行

**Comment by kuazhangxiaoai** [comment]
![P0123](https://user-images.githubusercontent.com/54108453/127162946-6f4d89ab-1bb2-41e9-94fd-a7aad200d20c.png)
![P0150](https://user-images.githubusercontent.com/54108453/127162993-cd2ae7cd-eebb-42bd-a7f2-327ca401f21b.png)
![P0305](https://user-images.githubusercontent.com/54108453/127163065-c70854f2-dde4-4771-b6eb-d07a7492e5af.png)
召回率不太好，总是把房子的一部分认定为small-vehicle。

**Comment by hukaixuan19970627** [comment]
可以尝试下下面的改动，是可以提点的：

detect后保存的结果是支持多类别预测的，但是用evaluation.py中进行result merge的时候没有添加这部分功能，你如果想从始至终都实现多类别预测的话可以做如下更改：（1）修改detect.py生成的txt格式，直接将检测结果分类并存入Task1_classname.txt中 (2) 再调用DOTA_devkit中的Result_merge_multiprocesses.py即可合并分割图像的检测结果 (3)直接调用DOTA_devkit中的dota_evaluation_task1.py输出评估结果；

**Comment by kuazhangxiaoai** [comment]
1.我直接对原图进行在线的切割和检测，没有用到evaluation.py中的result merge函数，用滑动窗口在线切割和用DOTA_devkit的先切割再识别的方法本质上有什么区别呢？
2、我取消了loadImages类里面的letterBox函数，取而代之的是：对不足1024的width或者height的全图的右侧和下侧进行pad灰条操作。取消resize操作对于最后的评估结果有什么不利影像？仅仅在图像右侧或者下侧进行补灰条，又有什么影像。
3、我使用过DOTA_devkit中对test set进行切割再识别再合并的方法，但其评估结果和我的方法差不多。我现在也很懵，我回去再试试。

**Comment by hukaixuan19970627** [comment]
> 1.我直接对原图进行在线的切割和检测，没有用到evaluation.py中的result merge函数，用滑动窗口在线切割和用DOTA_devkit的先切割再识别的方法本质上有什么区别呢？
> 2、我取消了loadImages类里面的letterBox函数，取而代之的是：对不足1024的width或者height的全图的右侧和下侧进行pad灰条操作。取消resize操作对于最后的评估结果有什么不利影像？仅仅在图像右侧或者下侧进行补灰条，又有什么影像。
> 3、我使用过DOTA_devkit中对test set进行切割再识别再合并的方法，但其评估结果和我的方法差不多。我现在也很懵，我回去再试试。

1. 没什么区别，不过要注意滑动窗口之间要存在gap区域。
2. 我印象里本来detect中letterBox就没开启, augment为true才会开启。detect.py是不需要确保图像宽高一致的，支持任意尺寸的图像输入，那个img_size设置为原图的尺寸就行（当然如果你的数据集没有小目标，img_size调小也是可以的），代码会自动在确保宽高ratio不变的前提下对图像进行resize + pad操作。pad为黑色/灰色没有影响，毕竟训练时的resize+pad就是补黑色区域，mosaic是补灰色区域，确保训练与推理流程一致就不会影响精度
3. 可以尝试我两天前说的那个提点方法，改一改评估代码就ok，dota数据集里面有多个类间差异小的物体，并且网络结构使用了sigmoid，所以对一个物体会有多种预测结果，但是我写的evaluation.py合并的时候只会保留置信度最高的结果再进行评估，所以一旦类别预测错误的框置信度最高，那么这个物体的预测结果就是FP，自然会影响mAP。

**Comment by kuazhangxiaoai** [comment]
![image](https://user-images.githubusercontent.com/54108453/127863643-7c68505b-36cb-47b6-9430-5c8c88348138.png)
按照您的方法，先切割再识别，果然提高了很多。但是我在线进行识别也不知道哪有问题，点数就是提不上来，我还得再改改。

**Comment by hukaixuan19970627** [comment]
> ![image](https://user-images.githubusercontent.com/54108453/127863643-7c68505b-36cb-47b6-9430-5c8c88348138.png)
> 按照您的方法，先切割再识别，果然提高了很多。但是我在线进行识别也不知道哪有问题，点数就是提不上来，我还得再改改。

这个精度差不多了，其实还能再调调上68，一些SOTA的多阶段检测器不加多尺度测试的话，mAP也就65 66的样子

**Comment by kuazhangxiaoai** [comment]
SOTA上面有几个76，78的算法，不知道怎么搞的。其中，CC类能到50+，他们说是用了Data augment，也不知道怎么搞的？

**Comment by hukaixuan19970627** [comment]
> SOTA上面有几个76，78的算法，不知道怎么搞的。其中，CC类能到50+，他们说是用了Data augment，也不知道怎么搞的？

论文里都会有说明的，一般带*号就说明使用了多尺度测试，一张测试图片以不同的尺度detect后再merge在一起，检测比赛的时候很常用，有些甚至会加旋转增强测试，一张图片以不同的旋转角度detect后再merge在一起。
没什么参考性，实际项目中完全用不到。最好只参考论文中的单尺度测试部分

**Comment by hukaixuan19970627** [comment]
不过你可以尝试一下，因为我也没试过多尺度测试的精度yolov5能达到多少，你可以利用devkit中的SplitOnlyImage.py先对test数据集进行多尺度的离线裁剪，然后再进行detect和merge，splitrate设为0.5 1.0 1.5即可

**Comment by kuazhangxiaoai** [comment]
您说，您没有在result_merge中加入multi-label预测，我看了您的代码，是不是主要是在nmsbynamedict那块没有根据类别进行nms呢？我gap设置的比较小，result-merge中的nms只能影响到gap里面的物体吧？应该影响不大吧？在mergebypoly这个函数中，我没有看到max相关的取最大值的方法。

**Comment by hukaixuan19970627** [comment]
> 您说，您没有在result_merge中加入multi-label预测，我看了您的代码，是不是主要是在nmsbynamedict那块没有根据类别进行nms呢？我gap设置的比较小，result-merge中的nms只能影响到gap里面的物体吧？应该影响不大吧？在mergebypoly这个函数中，我没有看到max相关的取最大值的方法。

merge是将多张切割后的图像检测结果合并在一起再做一次nms，所以这个地方不使用multi-class-nms的话，原先detect检测出来的其他类别结果也会被抑制掉

**Comment by stevenXS** [comment]
@kuazhangxiaoai 请问您在评估dota数据集一张图花费了多长时间呢？
