### ISSUE TITLE
关于模型大小的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#59]
![image](https://user-images.githubusercontent.com/54108453/127863386-07934a5a-83e4-48f8-9e39-644bc6b50e10.png)
请问，我用您的方法训练的模型，怎么和您公布的模型的大小差别这么大呢？
我用的Yolov5m.yaml文件。

**Comment by hukaixuan19970627** [comment]
模型在训练最后一个epoch完成之后会自动进行optimizer epoch results等信息的剔除，仅保留模型结构和对应参数，所以最终模型会小很多，两种模型的具体对比你可以直接将其打印出来观察其区别
