### ISSUE TITLE
训练时出现了问题，并且在推理是无效果

### ISSUE THREAD

**Issue by p110120p1** [hukaixuan19970627/YOLOv5_DOTA_OBB#6]
## ❔Question

作者你好，感谢你做的这个项目，我在使用自制数据集训练的时候出现了
![image](https://user-images.githubusercontent.com/54127320/112593946-2afb5700-8e43-11eb-8150-e83f7a452c98.png)
这个情况，请问是什么原因呢

**Comment by hukaixuan19970627** [comment]
1. 先使用demo文件进行训练，确保相关环境安装正确，train.py detect.py evaluation.py 这3个demo都有可视化结果，如果demo运行不成功，还请检查环境版本是否与reqirements.txt一致；
2. 训练自制训练集时，请确保labels的数据形式与ReadMe一致：
【classid    x_c   y_c   longside   shortside    Θ】    Θ∈[0, 180)

* longside: The longest side of the oriented rectangle.

* shortside: The other side of the oriented rectangle.

* Θ: The angle between the longside and the x-axis(The x-axis rotates clockwise)；x轴顺时针旋转遇到最长边所经过的角度
图示：
![image](https://user-images.githubusercontent.com/72599120/112602464-af9fa280-8e4e-11eb-8414-97db3292eb0a.png)

**Comment by p110120p1** [comment]
你好，我按照你之前说的进行了demo训练和推理都没问题，之后我使用自制数据集训练，发现对于大目标的效果好像不太好，请问这个如何处理

**Comment by hukaixuan19970627** [comment]
“效果不太好”这个描述过于宽泛，而且具体问题也需要具体分析。自制数据集目标大致是什么样的？大目标指的是哪一类目标？
根据你给出的图片来看，首先你的训练集规模太小，不足以支撑深度学习算法，因为这个项目是把θ作为分类任务来处理的，数据规模小原本就会引入类间不平衡的问题，而θ有180个分类，一旦数据规模不够类间不平衡产生的影响就会更大，特别是角度预测的准确率会大大降低；
另外，预测不出目标，这个问题不太具体。
是因为预测出来的框置信度太低？  —— 那么你就需要调低detect.py文件中的conf_thresh. 
预测使用的图片与训练集的图片特征分布完全不相关？  —— 那么预测不出框是正常现象。

**Comment by p110120p1** [comment]
![image](https://user-images.githubusercontent.com/54127320/112746677-0938d600-8fe3-11eb-9702-4dda2eaf919c.png)
就是类似于这种样的数据集，识别表针任务的，我大概每次训练400多轮，数据集为200多张，我在用原版yolov5训练的时候可以mAP能达到0.95，但是用旋转框这个只能把旋转点识别出来，表针要么识别不出来要么角度不对。你指的是这种旋转框任务得增加数据集？但是demo只有44张图片，训练400多轮也有不少目标被识别出来了，准确度也可以。

**Comment by hukaixuan19970627** [comment]
训练时生成的train_batch_0/1/2 三张图片能否发过来看看

**Comment by p110120p1** [comment]
![image](https://user-images.githubusercontent.com/54127320/112747146-07244680-8fe6-11eb-8ad6-853302b53e36.png)
![image](https://user-images.githubusercontent.com/54127320/112747157-16a38f80-8fe6-11eb-9a9b-50e92dcae8c8.png)
![image](https://user-images.githubusercontent.com/54127320/112747166-21f6bb00-8fe6-11eb-9f41-f8742441c36f.png)

**Comment by hukaixuan19970627** [comment]
看得出来labels定义没有出问题。
几点建议：
1.train时，终端打印了超出opencv定义范围的情况，这个需要解决，否则影响训练收敛，这个问题发生在general.py -> compute_loss -> rbox_iou -> longsideformat2poly -> longsideformat2cvminAreaRect函数中，即训练中计算损失函数时，需要计算旋转IoU，过程中需要把YOLO longside format转为poly format，但是转换中超出了定义范围，追溯回去的话应该是在某次预测中，θ被预测为180，但是预测值只可能是【0，179】180个分类值中的一个才对。麻烦你在general.py文件中做以下更改，再开始训练，方便我查找问题
![image](https://user-images.githubusercontent.com/72599120/112749039-4e183900-8ff2-11eb-82d9-f704b99dfa98.png)

2.从预测的图来看，框的中心位置预测是准确的，但就是θ分类出错，可能原因是数据规模太小，导致其中的物体的θ分布在【0，179】上是极度不均匀的，因此产生类间不平衡问题，解决办法：
在解决1问题的基础上，如果θ预测效果依然不好的话，可以尝试对数据集进行随机旋转增强，增加θ在数据集中的多样性

**Comment by p110120p1** [comment]
我之前调整了一下数据集标签格式，参考了一下你的DOTA2YOLO的代码，1问题没有再出现了。刚才发的推理图是在解决了1问题的基础上的效果。
![image](https://user-images.githubusercontent.com/54127320/112750126-35f7e800-8ff9-11eb-89d5-094fb35c2478.png)

![image](https://user-images.githubusercontent.com/54127320/112750066-d8639b80-8ff8-11eb-9436-4ecd0d4bf10e.png)
这三个yolov5自带的旋转增强没有动。请问像这种旋转框项目数据集一般为多少好一些呢？

**Comment by hukaixuan19970627** [comment]
我的代码里面涉及到旋转增强的只有水平镜像翻转，这种类型和规模的数据我建议你专门找找旋转增强的开源代码，比如旋转度数随机的数据扩增代码。200多张图片实在不适合用θ分类的检测器来训练，因为θ的分类太不均匀了，平均一下每个角度只有不到2张图片。
如果你解决不了数据集扩增的问题，那么适合你的应用场景的检测器符合以下特点：
1. 若选择anchor-based的检测器，每个anchor point生成的anchor框，不仅有scale、ratio区别，还有角度区别。
2. 尽量把θ作为回归任务来做，本项目使用的CSL是用分类来实现回归的思想，即从连续到离散的区别，这个过程中有精度损失，在数据集规模充分的情况下，损失可以接受，但显然你这个应用场景这种精度损失的作用被放大了

**Comment by p110120p1** [comment]
好的谢谢，那我找找旋转增强代码

**Comment by Wangfeng2394** [comment]
> 好的谢谢，那我找找旋转增强代码

找到了吗兄弟

**Comment by p110120p1** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
