### ISSUE TITLE
RuntimeError: Could not infer dtype of numpy.float32

### ISSUE THREAD

**Issue by hushuai1** [hukaixuan19970627/YOLOv5_DOTA_OBB#60]
您好，我在用您的demo进行测试的时候遇到了这个问题，
好像是这句代码的问题，求指点
`c = torch.tensor(labels[:, 0])  # classes`
Scanning labels DOTA_demo_view/labels.cache (44 found, 0 missing, 0 empty, 0 duplicate, for 44 images): 44it [00:00, 13217.03it/s]
Traceback (most recent call last):
  File "train.py", line 724, in <module>
    train(hyp, opt, device, tb_writer)
  File "train.py", line 311, in train
    c = torch.tensor(labels[:, 0])  # classes
RuntimeError: Could not infer dtype of numpy.float32
![image](https://user-images.githubusercontent.com/43898397/127964869-a56f39ad-c703-4706-ac31-cb178506195c.png)

**Comment by hukaixuan19970627** [comment]
先按照ReadMe.md中的installtion检察一下各个环境的版本是否匹配

**Comment by hushuai1** [comment]
感谢。确实是环境问题

**Comment by ghost** [comment]
请问是怎么解决的呢
