### ISSUE TITLE
关于多尺度训练的问题（About Multi－Scale Training）

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#62]
看这YOLOv5的多尺度训练的代码，有点儿不太对啊？
![image](https://user-images.githubusercontent.com/54108453/128315334-8864de95-23e2-47a5-85d1-40aa74242c10.png)
好像只改变了image，而对target好像并没有对应进行改变

**Comment by hukaixuan19970627** [comment]
你试着开启一下就知道了，trainbatch012可以直接查看经数据增强后的imgs和labels的可视化结果，原版的多尺度训练代码我没有改动过，应该是能正常使用的。labels的变换操作一般放在dataset.py中，把尺度因子传过去就行
