### ISSUE TITLE
(low confidence)我的问题时发现各个类别的检测的confidence比较低，算出来的presision也很低，具体如下：

### ISSUE THREAD

**Issue by root12321** [hukaixuan19970627/YOLOv5_DOTA_OBB#63]
## ❔Question
首先我这边使用的自己的数据集，总共10个类别，最后检测的各个类别ap如下：
0.702 | 0.432 | 0.61 | 0.3294 | 0.663 | 0.536 | 0.629 | 0.485 | 0.664
预处理的图片如下：
![image](https://user-images.githubusercontent.com/28287748/128589638-c52d0cd6-0f5b-4d57-8cfd-09f327b6fae6.png)
训练400epoch后的，最后的loss截图如下
![400epoch_loss](https://user-images.githubusercontent.com/28287748/128589666-3d1b6dfd-dafd-403f-b462-50127ea3965d.png)
最后感觉我检测结果的confidence比较低。而且存在较多的误检，导致了precision比较低

**Comment by root12321** [comment]
我再制作数据集的时候并没有把图片直接裁剪到1024*1024，而是原图的输入，标签也是针对原图归一化的

**Comment by root12321** [comment]
数据增强这块，我并没有使用moasiac和mixup

**Comment by hukaixuan19970627** [comment]
1. 数据增强要根据使用场景选择性使用，如果使用场景中不会出现路灯/电线杆倒过来的情况，那就不要开上下翻转增强
2. scale控制图像的尺度缩放比例范围，图像最终的scale为是random(1-scale,1+scale)，自行调节一下
3. 我看不出你的应用场景有任何使用旋转检测的必要，似乎水平检测就足以满足要求了，你直接用原版的yolov5不是更好吗，计算效率还更高
4. loss还远远没有收敛
5. 关于觉得confidence值太低，你可以参考这个issues：https://github.com/ultralytics/yolov5/issues/2864

**Comment by root12321** [comment]
主要是我这个检测有几个类别是旋转的目标，其他的类别都是水平的框

**Comment by root12321** [comment]
你的代码中不是没有使用多尺度训练吗，所以那个scale应该没有在训练中起到作用吧？

**Comment by hukaixuan19970627** [comment]
> 你的代码中不是没有使用多尺度训练吗，所以那个scale应该没有在训练中起到作用吧？

你指的多尺度是图像的size多尺度，是在数据增强之前完成的，比如图像会从原图的1024x1024变为1580x1580。yaml中的scale参数代表的流程是：图像先经过一定比例的resize后再crop出一个固定的size。比如原图1024x1024会先resize1580x1580，接着再crop出1024x1024的区域作为新的图像数据进入网络。
两者不冲突，你可以通过可视化直接观察它们的区别
