### ISSUE TITLE
（Pytorch Version/Install Pytorch）pytorch版本

### ISSUE THREAD

**Issue by Chenastron** [hukaixuan19970627/YOLOv5_DOTA_OBB#64]
## ❔Question
你们都是用什么版本的pytorch跑通的，1.6.0的根本就没有torch.backends啊。
这项目太粗糙了，心累
## Additional context
https://pytorch.org/docs/1.6.0/

**Comment by hukaixuan19970627** [comment]
![image](https://user-images.githubusercontent.com/72599120/128720834-b4ed2331-16e2-4786-a9e5-0f56e21472eb.png)
![image](https://user-images.githubusercontent.com/72599120/128720911-dfafa48f-2fdc-424c-bb64-a2823b33ed57.png)

**Comment by acai66** [comment]
https://github.com/hukaixuan19970627/YOLOv5_DOTA_OBB/issues/66
pytorch 1.9.0 测试OK。
