### ISSUE TITLE
关于您知乎上的focal loss的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#65]
您在知乎上说，focal loss 会降低yolov5的检测效果，yolov5会产生大量的低质量正样本，这是为什么呢？不太明白，正样本不是DOTA数据集提供的吗？yolov5怎么会产生正样本呢？

**Comment by hukaixuan19970627** [comment]
数据集提供真值GT，检测器训练的时候需要生成正负样本，正样本用于回归任务，正负样本用于分类任务

**Comment by kuazhangxiaoai** [comment]
> 数据集提供真值GT，检测器训练的时候需要生成正负样本，正样本用于回归任务，正负样本用于分类任务

那为什么您会说，yolov5会生成大量质量低下的正样本呢？正样本不是根据gt生成的吗？gt有多少个，就生成多少的正样本。

**Comment by hukaixuan19970627** [comment]
> > 数据集提供真值GT，检测器训练的时候需要生成正负样本，正样本用于回归任务，正负样本用于分类任务
> 
> 那为什么您会说：yolov5会生成大量质量低下的正样本呢？正样本不是根据gt生成的吗？gt有多少个，就生成多少的正样本，对吗？

额，你可以先看看知乎mmdetection 正负样本定义系列的文章，我记得是深度眸写的一个专栏。
每个gt仅生成一个正样本的检测器也有，比如一些anchor free的检测器。但是anchor based的检测器是基于max IoU原则来定义正样本的

**Comment by kuazhangxiaoai** [comment]
> 比gt多

我明白了,十分感谢
