### ISSUE TITLE
（Based yolov5 releases v6.0）感谢作者的代码，我成功在新版yolov5里移植了您的代码

### ISSUE THREAD

**Issue by acai66** [hukaixuan19970627/YOLOv5_DOTA_OBB#66]
## 🚀 Feature
非常感谢作者的贡献。
新版地址：https://github.com/acai66/yolov5_rotation

## Motivation

1. 更新的上游yolov5.
2. 完成在训练中评估性能
3. 解除矩形输入尺寸限制
4. 包含xml转标签脚本

## Additional context

1. 当前只完成train、val，并且训练初期 nms 时间过长。
2. ~~detect.py还未完成(导出onnx推理已测试OK)。~~ **已完成detect**

**Comment by hukaixuan19970627** [comment]
不错哟，有试过相关数据集上的精度吗。yolov5第五版刚出的时候我也把整个项目update了一下，但是dota上面的精度反而不如原版，结构上的改动就是CSP bottleneck换成了层数更少的C3，部分部件的激活函数换了一下，但是精度掉的比预想的多得多。

**Comment by acai66** [comment]
> 不错哟，有试过相关数据集上的精度吗。yolov5第五版刚出的时候我也把整个项目update了一下，但是dota上面的精度反而不如原版，结构上的改动就是CSP bottleneck换成了层数更少的C3，部分部件的激活函数换了一下，但是精度掉的比预想的多得多。

在我的数据集上性能好一些，dota没测试过

**Comment by stevenXS** [comment]
@acai66 作者您好，您的代码和原作者的代码都调试过了，但是同样的训练分辨率在您的代码batchsize只能支持一半。请问是哪里改动比较大吗

**Comment by acai66** [comment]
> @acai66 作者您好，您的代码和原作者的代码都调试过了，但是同样的训练分辨率在您的代码batchsize只能支持一半。请问是哪里改动比较大吗

有可能网络结构等有变，可以再试试原版yolov5在同分辨率的显存占用情况，公平起见，将原版yolov5的类别数加上180，如果还是显存还是差太多，我再研究下

**Comment by stevenXS** [comment]
@acai66 谢谢，我最近也再研究一下！

**Comment by stevenXS** [comment]
> > @acai66 作者您好，您的代码和原作者的代码都调试过了，但是同样的训练分辨率在您的代码batchsize只能支持一半。请问是哪里改动比较大吗
> 
> 有可能网络结构等有变，可以再试试原版yolov5在同分辨率的显存占用情况，公平起见，将原版yolov5的类别数加上180，如果还是显存还是差太多，我再研究下

@acai66 作者您好，我查看了yolo.py脚本，发现原作者的代码将一些卷积做了些替换，导致model的layers有所不同😂

**Comment by hukaixuan19970627** [comment]
我升级了一版新的，训练速度和精度相比老版本有很大提升
