### ISSUE TITLE
图像数据归一化的问题

### ISSUE THREAD

**Issue by root12321** [hukaixuan19970627/YOLOv5_DOTA_OBB#67]
## ❔Question

![image](https://user-images.githubusercontent.com/28287748/129006094-73aa9e4e-0ba6-4669-ad52-ea10b1a35826.png)
这里的
x[:, 1] - x[:, 3] / 2
x[:, 2] - x[:, 4] / 2
x[:, 1] + x[:, 3] / 2
x[:, 2] + x[:, 4] / 2
是你对长边表示法转poly的过程，但是我觉得这个转换的过程是有问题的，如下图：
![image](https://user-images.githubusercontent.com/28287748/129006135-d399815c-fcad-47d4-aaaa-a57b397aee5e.png)
可以看到长边表示法并不能确定长边对应的是x坐标还是y坐标，这就会导致转的poly其实是有问题的，我这个理解不知道对不对？

**Comment by acai66** [comment]
框不要竖过来，除非计算的需要，否则不考虑角度信息。对于你图中竖立的矩形，网络在训练与预测时都是以下面横着的框的方式进行的，在需要用到真实位置信息时才考虑旋转角度。
