### ISSUE TITLE
No result for precision recall 

### ISSUE THREAD

**Issue by nandini211995** [hukaixuan19970627/YOLOv5_DOTA_OBB#68]
![results](https://user-images.githubusercontent.com/66118595/129017062-94119559-0fbc-4b49-b4cd-57d74bd5f1c5.png)
Why is this happening? I am trying to train DOTAv1.0 . Kindly help me.

**Comment by hukaixuan19970627** [comment]
You can refer to this issue: #36

**Comment by acai66** [comment]
I ported the author’s rotation detection to the latest yolov5, which can monitor the status during training

**Comment by nandini211995** [comment]
Thank you @acai66 I try with this
