### ISSUE TITLE
YOLOv5版本问题（The baseline version about yolov5）

### ISSUE THREAD

**Issue by hushuai1** [hukaixuan19970627/YOLOv5_DOTA_OBB#69]
您好，我想问下您当初参考的是yolov5哪个版本的代码呀
![image](https://user-images.githubusercontent.com/43898397/129154070-201f3fb9-957a-4ca5-a244-723646058026.png)

**Comment by hukaixuan19970627** [comment]
2020.10月份 clone的代码，基于这个基础上改的

**Comment by hushuai1** [comment]
> 2020.10月份 clone的代码，基于这个基础上改的

谢谢大佬，我还想再问一下，您提供的YOLOv5的预训练模型也是当时一块clone下来的吗？您是否改了原版YOLOv5的一些层，我转tensorrt的出现了参数不一致的错误，感谢回复！

**Comment by hukaixuan19970627** [comment]
> > 2020.10月份 clone的代码，基于这个基础上改的
> 
> 谢谢大佬，我还想再问一下，您提供的YOLOv5的预训练模型也是当时一块clone下来的吗？您是否改了原版YOLOv5的一些层，我转tensorrt的出现了参数不一致的错误，感谢回复！

head层修改了。在原来的基础上添加了角度预测通道
