### ISSUE TITLE
mosaic

### ISSUE THREAD

**Issue by gengyanlei** [hukaixuan19970627/YOLOv5_DOTA_OBB#7]
你好，我看你的代码对于mosaic好像支持，但是处理和水平的没啥区别，请问你做mosaic了么？不太理解为啥与之前的没啥区别呢

**Comment by hukaixuan19970627** [comment]
你可以看看run/exp×/文件夹下的train_batch0/1/2图片，会显示数据增强之后的可视化结果。
另外YOLOv5改建详情请参考我的知乎文章，里面写的比较详细

**Comment by hukaixuan19970627** [comment]
你可以看看run/exp×/文件夹下的train_batch0/1/2图片，会显示数据增强之后的可视化结果。
另外YOLOv5改建详情请参考我的知乎文章，里面写的比较详细

**Comment by hukaixuan19970627** [comment]
一句话总结：旋转矩形框就是一个“带角度信息”的水平矩形框，与旋转有关的信息都在θ中，因此只要不涉及到角度类的数据增强，代码逻辑层面都不需要改动，添加θ维度就ok

**Comment by gengyanlei** [comment]
ok，之前一直思考的是边界用mosaic不好解决，对于放大的，xywh，对于wh裁剪的，和实际变化有区别。但是你这样操作，其实是将这部分区别忽略掉了，对于实际的训练影响较小
