### ISSUE TITLE
编译poly_nms_gpu模块的问题

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#72]
编译能够成功，但调用的时候总是出现类型不匹配的问题。
用的是windows平台。
ValueError: Buffer dtype mismatch, expected 'int_t' but got 'long long'
![image](https://user-images.githubusercontent.com/54108453/129647885-3fdbc134-32ce-4008-b685-d65f852bc7f6.png)

![image](https://user-images.githubusercontent.com/54108453/129647774-c440479d-18a1-438b-80ca-24cfd17db260.png)

**Comment by hukaixuan19970627** [comment]
windows能swig编译成功的人不多，我自己都没弄成功过呢。你可以用搜索引擎搜索关键词swig window DOTA_devkit，看看别人的教程
