### ISSUE TITLE
关于hyp中angle部分的超参数

### ISSUE THREAD

**Issue by phunix9** [hukaixuan19970627/YOLOv5_DOTA_OBB#73]
大佬你好，

非常喜欢你做的工作。

我在训练自定义数据时，超参数部分总是选不到合适的。请问你的hyp_finetune里是使用参数进化后的结果，还是自己经过实验得出的呢，谢谢！

**Comment by hukaixuan19970627** [comment]
调参一般靠经验比较好，根据几个loss的下降趋势来调整几个loss的权重，确保各个loss的下降趋势一致就ok
