### ISSUE TITLE
打标签工具

### ISSUE THREAD

**Issue by leiwentong** [hukaixuan19970627/YOLOv5_DOTA_OBB#77]
您好，不好意思，看了您知乎的文章，关于打标签的工具我还是不太清楚。能不能说得详细一点，谢谢啦~
另外：我之前做旋转目标检测用rolabelimg打标签，得到的xml文件是这样的，是否有方法能够转化为这个代码需要的标签文件格式呢？
![image](https://user-images.githubusercontent.com/77611811/130945091-087b5e50-e109-4282-a3ec-b2d9742ace7c.png)

**Comment by Yanhui-He** [comment]
@leiwentong 可以转，你找一个xml转txt的脚本，或者自己写一个，注意角度要从弧度变成角度。
