### ISSUE TITLE
图像边缘bounding box偏移问题

### ISSUE THREAD

**Issue by Yanhui-He** [hukaixuan19970627/YOLOv5_DOTA_OBB#78]
@hukaixuan19970627 你好，请问你在测试的时候有出现过图像边缘目标框偏移问题吗？

大部分结果还可以，就是在图像边缘的目标框会偏移一部分距离，random_perspective我用的是v5原版的代码。

还有我看你在`random_perspective` 注释掉了`apply angle-based reduction of bounding boxes`，是这个效果不好吗？

Ah! 我看到degree设置的为0，所以`apply angle-based reduction of bounding boxes`这个不需要了。

**Comment by hukaixuan19970627** [comment]
方便发个图看看是什么样的偏移么
