### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by kuazhangxiaoai** [hukaixuan19970627/YOLOv5_DOTA_OBB#79]
## Additional context
看您用的是yolov5官方发布的预训练模型。看您把1-9层的backbone部分freeze了。yolov5官方的参数能很好的提取DOTA数据集的特征吗？您修改了Detect层的结构，结构变了，为什么模型能正确加载呢？
谢谢

**Comment by hukaixuan19970627** [comment]
1. 如果新场景目标特征分布与coco相差太远的话，不建议冻结backbone部分
2.  模型参数是每层顺序加载的，前面的结构和checkpoints是可以对应上的，所以可以加载成功，detect部分由于结构改变，因此detect层不会载入checkpoints部分的参数
