### ISSUE TITLE
训练的时候输入不是640的话，预测不出来框

### ISSUE THREAD

**Issue by jiarenyf** [hukaixuan19970627/YOLOv5_DOTA_OBB#8]
发现训练的时候输入如果不是640大小的话，训出来的模型预测不出框。只有输入大小是640训练的，才能在预测的时候出现框，这是为什么呢？麻烦作者看下，谢谢。

**Comment by hukaixuan19970627** [comment]
是demo文件还是自制的数据集出现这种情况呢？
（白天知乎找我的话我回复会及时一点）

**Comment by jiarenyf** [comment]
> 是demo文件还是自制的数据集出现这种情况呢？

是自己的数据集

**Comment by hukaixuan19970627** [comment]
预测不出框，调低conf-thresh

**Comment by Allenstin** [comment]
调低那些阈值都没用，训练时候，排在后面的指标全是0。

**Comment by hukaixuan19970627** [comment]
[
epoch/epochs-1 , mem , loss_obx , loss_obj , loss_cls ,loss_angle ,
total_loss , targets_num , imgs.shape, precision , recall , mAP@.5 ,
mAP@.5-.95, val_loss_box, val_loss_obj, val_loss_cls， val_loss_angle
]
由于删除了在线评估程序，所以后续8个评估数据都是0是正常现象，旋转目标的评估方式比较特别，我另外写了一个evaluation.py。

**Comment by jiarenyf** [comment]
> [
> epoch/epochs-1 , mem , loss_obx , loss_obj , loss_cls ,loss_angle ,
> total_loss , targets_num , imgs.shape, precision , recall , mAP@.5 ,
> mAP@.5-.95, val_loss_box, val_loss_obj, val_loss_cls， val_loss_angle
> ]
> 由于删除了在线评估程序，所以后续8个评估数据都是0是正常现象，旋转目标的评估方式比较特别，我另外写了一个evaluation.py。

我把test.py里面的test函数补全了，用poly_iou计算pred与target的iou进行匹配，在输入640大小的时候，是可以输出p/r/map这些的，指标可以训的比较高。但是用1024/1536这些大小输入的话，p/r/map指标都是0。。。

**Comment by hukaixuan19970627** [comment]
emmm, 不清楚，能否把你的数据集情况发过来看看。
另外预测不出框，是置信度调到0.05也不出框吗？如果是这样的话我去检查一下代码问题
