### ISSUE TITLE
数据集放在哪

### ISSUE THREAD

**Issue by leiwentong** [hukaixuan19970627/YOLOv5_DOTA_OBB#80]
## ❔Question
不好意思，请问一下自己的数据集放在代码的哪个文件里？data那？放在代码里的数据集格式就是txt吗，还要通过代码转化成其他吗？

**Comment by hukaixuan19970627** [comment]
你可以按照readme把所有步骤都走一遍。train_detect_evaluation_demo_files里面有整套流程的demo数据
