### ISSUE TITLE
训练自己的数据集,拟合并不理想

### ISSUE THREAD

**Issue by zhaoguoqing12** [hukaixuan19970627/YOLOv5_DOTA_OBB#82]
![image](https://user-images.githubusercontent.com/47818312/132692876-d9ed6a55-329b-4429-bd4e-fca98823d4bf.png)
![train_batch0](https://user-images.githubusercontent.com/47818312/132693136-2284c5ef-6556-4b43-93ac-be5e93bc37a8.jpg)
![train_batch1](https://user-images.githubusercontent.com/47818312/132693157-1927a7d3-3ab1-49cf-bd31-fddfe0f1f10d.jpg)
![train_batch2](https://user-images.githubusercontent.com/47818312/132693167-b9a3b5e0-79fe-4540-a5ab-ddd4768b238b.jpg)

测试自己的数据不是很理想,帮忙看一下吧
1.似乎box loss 以及 angle loss并没有收敛，两分类，只不过数据量差距较大。
![labels](https://user-images.githubusercontent.com/47818312/132693355-ed013983-ed77-4b40-82f0-03a05ec58c9e.png)
2.超参数并没有修改，训练了80周期loss不下降啦,数据集在2000张左右,效果远远没有达到预期。

**Comment by hukaixuan19970627** [comment]
接着训练完的权重继续训练。
mosaic关闭，水平翻转关闭，剩下翻转关闭，你的场景不适合用这些数据增强策略

**Comment by zhaoguoqing12** [comment]
> 接着训练完的权重继续训练。
> mosaic关闭，水平翻转关闭，剩下翻转关闭，你的场景不适合用这些数据增强策略
谢谢 我会试试的
