### ISSUE TITLE
单目标动态检测时检测框发生形变

### ISSUE THREAD

**Issue by yang5818** [hukaixuan19970627/YOLOv5_DOTA_OBB#83]
## ❔Question
您好，我在进行单目标动态识别的过程中，检测框发生了形变，变成了一个细长的条形，请问一下这是为什么呢？

https://user-images.githubusercontent.com/90511626/132948343-68674928-c1bf-468b-aed2-71b225269406.mp4

**Comment by hukaixuan19970627** [comment]
这个问题有解决吗

**Comment by yang5818** [comment]
我标签转换的时候转换错了  后来发现了改完了就解决了  谢谢大佬！
