### ISSUE TITLE
标签可视化和训练时标签不一致问题

### ISSUE THREAD

**Issue by Ellsionjeep** [hukaixuan19970627/YOLOv5_DOTA_OBB#85]
## ❔Question
请问大佬，为什么我的标签可视化正常，而训练时标签的框有偏移和大小不一致的问题？

## Additional context
训练时的标签![train_batch0](https://user-images.githubusercontent.com/55690137/133221090-ab011db6-ba79-4be6-93c9-4812d158009d.jpg)
可视化的标签![afternoon-frame22600_](https://user-images.githubusercontent.com/55690137/133221233-3b39009c-d1ee-4269-b3f5-4120776f6381.jpg)

**Comment by hukaixuan19970627** [comment]
原因在这里https://zhuanlan.zhihu.com/p/385701722
你可以直接让图像宽高一致，就不会有label偏移的问题出现
