### ISSUE TITLE
关于rotate_box_iou中的boxes数量问题

### ISSUE THREAD

**Issue by stevenXS** [hukaixuan19970627/YOLOv5_DOTA_OBB#87]
## ❔Question
作者您好，general.py中的def rotate_box_iou(box1, box2, GIoU=False)方法中box1.shape == box2.shape一定要相等才是正确的吗？

**Comment by hukaixuan19970627** [comment]
这个地方的RIoU计算是为了一对一计算正样本anchor与gt box之间的旋转IoU，那肯定要维度一致啊

**Comment by stevenXS** [comment]
@hukaixuan19970627 我在写test函数时遇到了这么一个现象：

- box1(n, [xywhθ]) 和 box2(m, [xywhθ]) 的 [xywhθ]是一致的，不过box2作为预测方它预测出来的个数m不等于n，我进行逐一匹配可以么

**Comment by hukaixuan19970627** [comment]
> @hukaixuan19970627 我在写test函数时遇到了这么一个现象：
> 
> * box1(n, [xywhθ]) 和 box2(m, [xywhθ]) 的 [xywhθ]是一致的，不过box2作为预测方它预测出来的个数m不等于n，我进行逐一匹配可以么

test部分原理不一样的，评估要确定TP和FP的数量，所以计算旋转IoU时基本都是一个GT框对应多个预测框，不能直接用这个函数，你可以根据这个RIoU函数的实现细节写一个专门用于评估用的旋转IoU函数

**Comment by stevenXS** [comment]
@hukaixuan19970627 明白了，谢谢作者
