### ISSUE TITLE
（mAP@0.5 on DOTAv1.5）关于评估函数中mAP和loss问题

### ISSUE THREAD

**Issue by stevenXS** [hukaixuan19970627/YOLOv5_DOTA_OBB#90]
## ❔Question
作者您好，根据您的代码修改了一个评估函数，但是目前训练部分的angle loss始终下不去，不知道现在的训练数据是否正常，麻烦作者帮我参考一下（_目前迭代到90多个epoch时，angle loss基本不怎么变化_）。

## Additional context

- 预训练模型加载的`yolov5x.pt`；
- results部分训练结果图：
![image](https://user-images.githubusercontent.com/53604654/134293854-2b161fa9-e885-4c64-92ea-9070afaed918.png)

**Comment by hukaixuan19970627** [comment]
你可以直接查看tensorboard来可视化loss的下降情况，从我这边看的话整体趋势依旧是在下降的，mAP也在逐步上涨，期间有上下浮动不挺正常的嘛。
如果希望angle cls obj box四个loss的下降趋势保持一致的话，可以调节一下各loss的权重。例如现在就中断训练进程，接着87epoch的checkpoint调整完loss权重后继续训练就可以。
另外每个epoch都评估的话挺费时间的，旋转IoU的计算效率并不高，可以改成每隔5/10个epoch评估一次。
想直观查看训练情况是否正常的话，可以一边训练一边用checkpoint进行detect，直接可视化检测结果就行，一般yolo系列对于dota数据集来说50个epoch已经有不错的检测效果了

**Comment by stevenXS** [comment]
嗯嗯，谢谢作者，我再尝试一下

**Comment by stevenXS** [comment]
@hukaixuan19970627 作者您好，我在DOTA-v1.5数据集上评估完后，总体精度大约在67左右，目前主流的SOTA精度似乎都80左右。 难道是一阶段算法本身的局限性吗，这个精度差距还是蛮大的😂

**Comment by hukaixuan19970627** [comment]
> @hukaixuan19970627 作者您好，我在DOTA-v1.5数据集上评估完后，总体精度大约在67左右，目前主流的SOTA精度似乎都80左右。 难道是一阶段算法本身的局限性吗，这个精度差距还是蛮大的😂

做对比的话要公平对比，数据集要对齐，tricks也要对齐，你可以使用多尺度测试和旋转增强测试后再对比性能
![image](https://user-images.githubusercontent.com/72599120/134793997-bbb2afdc-d3fd-4027-8fd9-8d0c1e6f7d73.png)

**Comment by hukaixuan19970627** [comment]
#58

**Comment by stevenXS** [comment]
@hukaixuan19970627  突然给忘了，大家一般都是在1024上做的，我再试试。谢谢
