### ISSUE TITLE
为什么自己的数据集训练完成后检测框出奇的大甚至出界

### ISSUE THREAD

**Issue by LJiHONG** [hukaixuan19970627/YOLOv5_DOTA_OBB#91]
## ❔Question
为什么我训练完之后，检测框出奇的大，还会出界呢？

**Comment by hukaixuan19970627** [comment]
数据集具体情况，在原始项目的基础上改了哪些地方，trainbatch0/1/2，loss曲线图，detect可视化图等一切能描述清楚问题的东西一起上传一下

**Comment by hukaixuan19970627** [comment]
从loss曲线上看的话，10个epoch后loss就没有变化了，说明网络在后期可能一直没有向最小值收敛。
看数据集的话，你的应用场景似乎并不需要检测角度，水平检测的yolov5就可以满足你的需求，用旋转检测反而可能出问题
