### ISSUE TITLE
测试时，检测结果有很多检测框，并且检测框有的超出边界

### ISSUE THREAD

**Issue by HeyMrYu** [hukaixuan19970627/YOLOv5_DOTA_OBB#93]
## ❔Question

另外，模型的输出我看都是大于1的数，请问，模型输出是反归一化后的结果么
## Additional context
![image](https://user-images.githubusercontent.com/44186937/135064724-397a299a-09a3-4359-b15c-03e98104e72d.png)

**Comment by hukaixuan19970627** [comment]
数据集具体情况，在原始项目的基础上改了哪些地方，trainbatch0/1/2，loss曲线图，detect可视化图等一切能描述清楚问题的东西都上传一下。
模型检测层的输出值理论上是归一化的数据
