### ISSUE TITLE
训练HRSC2016数据集box损失不下降，最终detect没有检测框

### ISSUE THREAD

**Issue by cxt321** [hukaixuan19970627/YOLOv5_DOTA_OBB#94]
## ❔Question
感谢大佬的分享！
我用的数据集为HRSC2016，图片格式为bmp，其他步骤和处理DOTA一样；
最终detect没有txt输出，显示什么都没检测到，查看损失发现box未下降；
以下是result和train_batch0-2：
![results](https://user-images.githubusercontent.com/69035512/135195782-fdbde658-bef1-4b39-8775-01ef7214c889.png)
![train_batch0](https://user-images.githubusercontent.com/69035512/135195791-2aabebf0-e100-41cf-9233-497a949865c1.jpg)
![train_batch1](https://user-images.githubusercontent.com/69035512/135195793-c441f597-949f-42ca-ae13-eb1c208cf1c1.jpg)
![train_batch2](https://user-images.githubusercontent.com/69035512/135195796-f7335b60-492a-465b-81d0-37e39e3ffed9.jpg)

**Comment by wuyifan2233** [comment]
我也是遇到了同样的问题，我训练出来的图片和你一样的情况，目前还在排查中

**Comment by hukaixuan19970627** [comment]
yolov5不支持单目标识别，你可以参考这里的常见问题汇总：https://zhuanlan.zhihu.com/p/358072483
